### ISSUE TITLE
incorrect file path for $ENV{'BLAST_PATH'} when installing

### ISSUE THREAD

**Issue by jbadomics** [eead-csic-compbio/get_homologues#1]
When running `perl install.pl` I kept getting the following error:

```
### 1) checking required parts: 


## checking mcl-14-137 (lib/phyTools: $ENV{'EXE_MCL'})
>> OK
## checking COGsoft/COGlse (lib/phyTools: $ENV{'EXE_COGLSE'})
>> OK
## checking COGsoft/COGtriangles (lib/phyTools: $ENV{'EXE_COGTRI'})
>> OK
## checking COGsoft/COGmakehash (lib/phyTools: $ENV{'EXE_MAKEHASH'})
>> OK
## checking COGsoft/COGreadblast (lib/phyTools: $ENV{'EXE_READBLAST'})
>> OK
## Checking blast (lib/phyTools: $ENV{'EXE_BLASTP'})
<< Cannot run shipped blastp, please download it from ftp.ncbi.nih.gov/blast/executables/blast+/LATEST/ ,
<< install it and edit variable BLAST_PATH as explained in the manual
<< (inside set_phyTools_env in file lib/phyTools.pm) .
<< Then re-run
```

While I do have a newer version of BLAST+ (2.31) installed, the included version is sufficient but the `$ENV{'EXE_BLASTP'}` variable in `lib/phyTools.pm` is incorrect. As declared in `lib/phyTools.pm` line 70 the path is

    { $ENV{'BLAST_PATH'} = $ENV{'MARFIL'}.'bin/ncbi-blast-2.2.27+/bin/'; }

but the correct path is

    { $ENV{'BLAST_PATH'} = $ENV{'MARFIL'}.'bin/ncbi-blast-2.2.27+/bin/bin/'; }

The issue can be resolved either by creating symbolic links to the executables in `bin/ncbi-blast-2.2.27+/bin/` or by modifying `lib/phyTools.pm` to the full path of the bundled BLAST+ executables.

**Comment by eead-csic-compbio** [comment]
Thanks Jon, this is fixed on release 20151229 (v2.0.1).
