### ISSUE TITLE
Error with FNA and FAA sequence order

### ISSUE THREAD

**Issue by brettChapman** [eead-csic-compbio/get_homologues#102]
Hi

I've just downloaded the latest version of Get_Homologous-EST and I'm now getting this error when running:

```
# /data/get_homologues/get_homologues-est.pl -d cds -o 1 -i 40 -e 0 -r Morex.fna -t all -c 0 -z 0 -I 0 -m cluster -n 2 -M 0 -C 75 -S 95 -E 1e-05 -F 1.5 -b 0 -s 0 -D 1 -R 0 -L 0 -A 0 -P 0

# computer cluster settings
# CHKEXE	squeue
# CTIME	30
# DELEXE	scancel
# ERROR	F
# PATH	
# QARGS	
# STIME	1
# SUBEXE	sbatch
# TYPE	slurm

# version 15062022
# results_directory=/data/pangenome_cluster_analysis_MorexV3/cds_est_homologues
# parameters: MAXEVALUEBLASTSEARCH=0.01 MAXPFAMSEQS=250 BATCHSIZE=1000 MINSEQLENGTH=20 MAXSEQLENGTH=25000

# checking input files...
# same_sequence_order : sequence #1462 does not match: ATGGCGAGAACCCTCTTTGGTTTTGTCGCCGCCGCCGTGCTCCTCCTCGCCGTCCTCATGCCGGCCCTCGCCGCCGCGCAGGCCCCCGCACCGGCGCCCACCAGCGACGCGTCTTCGATCGACCAGGGCGTCGCCTACCTTCTGATGATCGTGGCGCTGGTGCTCACCTACCTCATCCACCCGTTGGACGCCTCN
MARTLFGFVAAAVLLLAVLMPALAAAQAPAPAPTSDASSIDQGVAYLLMIVALVLTYLIHPLDAS
MARTLFGFVAAAVLLLAVLMPALAAAQAPAPAPTSDASSIDQGVAYLLMIVALVLTYLIHPLDAX
# WARNING: cannot use protein sequences in file cds/Akashinriki.faa
# as they do not match those in file cds/Akashinriki.fna

# WARNING: -D Pfam domain scans cannot be performed without input protein sequences (please check the manual)

# Akashinriki.fna 44446 srun: error: node-1: task 0: Exited with exit code 255
```

I used to run with an older version (around a yr or 2 older) without any problems. I've checked the order of the sequence in both FNA and FAA and they're exactly the same, so I don't understand where this error is coming from.

In the error sequence ```MARTLFGFVAAAVLLLAVLMPALAAAQAPAPAPTSDASSIDQGVAYLLMIVALVLTYLIHPLDAS``` is present, but the actual protein sequence for that sequence is ```MARTLFGFVAAAVLLLAVLMPALAAAQAPAPAPTSDASSIDQGVAYLLMIVALVLTYLIHPLDAX``` so not sure what's happening there.

Thanks.

**Comment by brettChapman** [comment]
The last nucleotide is N, so this may be an issue with how it's handling ambiguous nucleotides/amino acids?

**Comment by eead-csic-compbio** [comment]
Hi @brettChapman , a new check was added recently, 

https://github.com/eead-csic-compbio/get_homologues/blob/4851ae7d99ebd2096970bce76d0d83772fde36b4/lib/phyTools.pm#L577

After your report I guess we need to relax it a little bit so that sequences with N or X residues are permitted.

**Comment by eead-csic-compbio** [comment]
Can you please update with git pull to include the latest change https://github.com/eead-csic-compbio/get_homologues/commit/34ba8c7f84cd01ea9315f585c4f128af30b979be ?
Let me know if this works,
Bruno

**Comment by brettChapman** [comment]
Hi Bruno

I just updated and ran again, unfortunately the error still comes up. I checked the phyTools.pm code to check if the new line of code is in there, and it definitely is.

**Comment by eead-csic-compbio** [comment]
Please pull again after https://github.com/eead-csic-compbio/get_homologues/commit/70749cb0ccb618d991886e63ab078bef00cdaeb3 and let me know whether it works now. I might take a day or two to respond,
Bruno

**Comment by brettChapman** [comment]
Thanks Bruno, all seems to be working now
