### ISSUE TITLE
File Output?

### ISSUE THREAD

**Issue by TommyH-Tran** [eead-csic-compbio/get_homologues#103]
Is there a file that will identify the the core, soft core, shell, and cloud genes per genome? I know in the pangenome matrix analysis it outputs it in the terminal, but I was wondering if it outputs a file with this information and what the name is?

-T

**Comment by eead-csic-compbio** [comment]
Hi @TommyH-Tran ,
the script parse_pangenome_matrix.pl -s can produce 4 files with clusters in the cloud, shell, soft-core and core compartments, as explained [here](http://eead-csic-compbio.github.io/get_homologues/manual/#shellplot).

Now, those files contain cluster names, you will have to do extra work to get the actual genes from a genome of interest, for example in the command line; please let us know if you need with that. 

Another approach would be to check the pangenome_matrix_genes_t0.tab matrix produced by script compare_clusters.pl -m, which actually contains the gene names in each cluster, as explained in the latest [tutorial](http://eead-csic-compbio.github.io/get_homologues/plant_pangenome/protocol.html#pangenome-analyses)

Hope this helps,
Bruno

**Comment by eead-csic-compbio** [comment]
I have added this to the EST [manual](http://eead-csic-compbio.github.io/get_homologues/manual-est/manual-est.html#SECTION00054000000000000000)

**Comment by TommyH-Tran** [comment]
@eead-csic-compbio thank you for your clarification Bruno
