### ISSUE TITLE
Error: find_COGs

### ISSUE THREAD

**Issue by Pirxtrurl** [eead-csic-compbio/get_homologues#105]
Hello,

My name is Jorge Val. Currently, I am working as a postdoc at the University of Edinburgh.

![image](https://user-images.githubusercontent.com/104511273/196253063-61896d2c-68eb-4380-bc7c-1f2b119ea857.png)
****

The only difference in this run was the size of the set. It was 133  large microbial genomes (from 5 Mbps to 11 Mbps). 

I try to solve it by myself, but I couldn't. 

I check the get_homologues installation and it seems correct:

![image](https://user-images.githubusercontent.com/104511273/196253444-1a519bde-2ead-4125-a1cc-af3d9e6262db.png)

Please, could you help me?

Best regards,

Jorge

**Comment by eead-csic-compbio** [comment]
Hi @Pirxtrurl , your error message seems to come from this line:

https://github.com/eead-csic-compbio/get_homologues/blob/5ecfd035dddb9157b396324097bd268eab60d6cb/lib/marfil_homology.pm#L2795

The comments in that part of the code indicate that sometimes disk latency might cause trouble as COGs writes large files, often simply re-running sorts things out. However, this might also be a RAM bottleneck problem, for which you might try option -s or a larger computer.

The failed job should leave behind at least three files (cog-edges.txt, all-edges.txt and all.cog.clusters.log), these might help you track down the problem further,
let me know how this goes,
Bruno

**Comment by Pirxtrurl** [comment]
Thanks for your quick answer.

I also suspected it was a problem due to the volume of data. I have tried restarting the analysis several times, but it keeps giving me the same error. I guess the algorithm must reach some bottleneck, as you suggest. Unfortunately, I don't have another computer with more capacity. 

I have drastically reduced the number of genomes I use as input. I hope this will avoid crashing the analysis. I will also try to repeat the same run by adding the -s option. Perhaps with this option activated, the program can complete the analysis.

Anyways, thanks for your help.

Best regards.

Jorge

**Comment by eead-csic-compbio** [comment]
If you don't mind sharing your input .gbk files I can try and run it here and see how taht goes, it is still possible that some code needs fixing,
Bruno

**Comment by eead-csic-compbio** [comment]
Sure

**Comment by eead-csic-compbio** [comment]
Available RAM for this job was 32GB
