### ISSUE TITLE
COGreadblast produce empty results

### ISSUE THREAD

**Issue by RiversDong** [eead-csic-compbio/get_homologues#106]
I am using COG making algorithm to produce my own ortholog group for more than 100 genomes. According to readme reporting at COGsoft.201204/Readme.2012.04.txt downloaded at https://ftp.ncbi.nih.gov/pub/wolf/COGs/COGsoft/COGsoft.201204.tar. I encountered a confusion when using COGreadblast. This program produced empty results for self.csv, query2subject.csv and hits.csv.

Here are the details:
Command: 
COGreadblast -d=/home/chuand/giant_virus/result/BLASTconv -u=/home/chuand/giant_virus/result/BLASTno -f=/home/chuand/giant_virus/result/BLASTff -s=/home/chuand/giant_virus/result/BLASTno -e=0.1 -q=2 -t=2

The blast results (BLASTno.tab and BLASTff.tab) were stored in /home/chuand/giant_virus/result/BLASTno, and /home/chuand/giant_virus/result/BLASTff. Format looks like as following:
![image](https://user-images.githubusercontent.com/45725241/199979477-690fe44c-4672-408e-b6b0-d64bfc7d486b.png)
  
The format of hash.csv looks like
![image](https://user-images.githubusercontent.com/45725241/199979441-ed79076c-05c0-4271-a1c3-8d8ee1124ecc.png)

**Comment by eead-csic-compbio** [comment]
Hi @RiversDong , this is not a GET_HOMOLOGUES question. However, I suggest you run get_homologues.pl -G with (a subset of) your data and see how the files are formatted for COG,
Bruno

**Comment by RiversDong** [comment]
Thanks for your kindly help. This is very helpful
