### ISSUE TITLE
Unable to create venn intersection BDBH, COGS, OMCL

### ISSUE THREAD

**Issue by TommyH-Tran** [eead-csic-compbio/get_homologues#108]
I can not create a intersection using `./compare_clusters.pl` I have checked inside the folders and the .faa and .fna gene clusters are present. Then the error said to review the duplicated.cluster_list file and it is completely blank. 

**Here is the output:**

---
```
# ./compare_clusters.pl -d /Users/klemonlab/Downloads/LG180_f0_19taxa_algBDBH_e0_C90_,/Users/klemonlab/Downloads/LG180_f0_0taxa_algCOG_e0_C90_,/Users/klemonlab/Downloads/LG180_f0_0taxa_algOMCL_e0_C90_ -o /Users/klemonlab/Desktop/THT/THT_NACH/intersection_19 -n 0 -m 0 -t 19 -I  -r 0 -s 0 -x 0 -T 0

# output directory: /Users/klemonlab/Desktop/THT/THT_NACH/intersection_19
# WARNING: output directory /Users/klemonlab/Desktop/THT/THT_NACH/intersection_19 already exists, note that you might be mixing clusters from previous runs


# number of input cluster directories = 3

# parsing clusters in /Users/klemonlab/Downloads/LG180_f0_19taxa_algBDBH_e0_C90_ ...
# cluster_list in place, will parse it (/Users/klemonlab/Downloads/LG180_f0_19taxa_algBDBH_e0_C90_.cluster_list)
# number of clusters = 270 duplicated = 0
# parsing clusters in /Users/klemonlab/Downloads/LG180_f0_0taxa_algCOG_e0_C90_ ...
# cluster_list in place, will parse it (/Users/klemonlab/Downloads/LG180_f0_0taxa_algCOG_e0_C90_.cluster_list)
# number of clusters = 0 duplicated = 0
# parsing clusters in /Users/klemonlab/Downloads/LG180_f0_0taxa_algOMCL_e0_C90_ ...
# cluster_list in place, will parse it (/Users/klemonlab/Downloads/LG180_f0_0taxa_algOMCL_e0_C90_.cluster_list)
# number of clusters = 0 duplicated = 0

# duplicated list: /Users/klemonlab/Desktop/THT/THT_NACH/intersection_19/duplicated.cluster_list (please review)

# intersection size = 0 clusters

# ERROR: cannot proceed with null intersection
```
---

**Comment by eead-csic-compbio** [comment]
Hi @TommyH-Tran ,
can you please share the LG180_f0_0taxa_algCOG_e0_C90_.cluster_list and LG180_f0_0taxa_algOMCL_e0_C90_.cluster_list files? It would also help to see the output of the ls command at LG180_f0_0taxa_algCOG_e0_C90_ and LG180_f0_0taxa_algOMCL_e0_C90_ respectively,
thanks,
Bruno

**Comment by TommyH-Tran** [comment]
I `cd` into both of those directories and then did `ls` and the gene cluster files show up in the terminal


<img width="1115" alt="ScreenShot 2023-06-12 at 03 33 21" src="https://github.com/eead-csic-compbio/get_homologues/assets/60275107/8c1adbe2-4679-46b1-9890-f0e8da299714">

<img width="1115" alt="ScreenShot 2023-06-12 at 03 33 49" src="https://github.com/eead-csic-compbio/get_homologues/assets/60275107/fabb34ef-d5bf-4685-a809-325d4a3a735d">

**Comment by eead-csic-compbio** [comment]
Sorry @TommyH-Tran , cannot see what wrong so far. Would it be possible for you to send me the folders LG180_f0_0taxa_algCOG_e0_C90_ ,  LG180_f0_0taxa_algOMCL_e0_C90_ and LG180_f0_19taxa_algBDBH_e0_C90_ compressed?
Thanks,
Bruno

**Comment by TommyH-Tran** [comment]
Here are the folders:
[LG180_f0_0taxa_algCOG_e0_C90_.zip](https://github.com/eead-csic-compbio/get_homologues/files/11729014/LG180_f0_0taxa_algCOG_e0_C90_.zip)
[LG180_f0_0taxa_algOMCL_e0_C90_.zip](https://github.com/eead-csic-compbio/get_homologues/files/11729015/LG180_f0_0taxa_algOMCL_e0_C90_.zip)
[LG180_f0_19taxa_algBDBH_e0_C90_.zip](https://github.com/eead-csic-compbio/get_homologues/files/11729016/LG180_f0_19taxa_algBDBH_e0_C90_.zip)

**Comment by eead-csic-compbio** [comment]
Thanks @TommyH-Tran , it seems the reason for this output is the optional argument -t 19, which requires clusters in the intersection to contain exactly 19 sequences (single-copy)  from 19 taxa. As you can see below, there are none among OCML / COG clusters:

    grep -c "size=19 taxa=19" LG180_f0_19taxa_algBDBH_e0_C90_.cluster_list 
    270
    grep -c "size=19 taxa=19" LG180_f0_0taxa_algCOG_e0_C90_.cluster_list
    0
    grep -c "size=19 taxa=19" LG180_f0_0taxa_algOMCL_e0_C90_.cluster_list 
    0

If you remove it the resulting intersection contains 144 clusters.
Hope this helps,
Bruno

**Comment by TommyH-Tran** [comment]
Could I not run COG and OMCL like this to get single copy and then do the `./compare_clusters.pl` ? Or are you suggesting instead I add the -S and -e ontop of those two runs?  

`./get_homologues.pl -d "/Users/klemonlab/Desktop/THT/THT_NACH/NACH_gbk_19" -n 8 -t 19 -C 90 -G`

`./get_homologues.pl -d "/Users/klemonlab/Desktop/THT/THT_NACH/NACH_gbk_19" -n 8 -t 19 -C 90 -M`

**Comment by eead-csic-compbio** [comment]
This is what I suggest, if 90% identity is reasonable for your analysis:

    ./get_homologues.pl -d "/Users/klemonlab/Desktop/THT/THT_NACH/NACH_gbk_19" -n 8 -t 19 -C 90 -G -S 90 -e

    ./get_homologues.pl -d "/Users/klemonlab/Desktop/THT/THT_NACH/NACH_gbk_19" -n 8 -t 19 -C 90 -M -S 90 -e

**Comment by TommyH-Tran** [comment]
I tried using what you suggested and still get 0 clusters. Is 90% identity too rigid?

**Comment by eead-csic-compbio** [comment]
It's probably too lenient. If you want single copy-clusters you need to separate the divergent copies, so you should increase it even more to see if that works,
Bruno

**Comment by TommyH-Tran** [comment]
Sorry for the delay, I set it at 99 limit and it still gave me back 0 clusters using the flags you suggested...

`./get_homologues.pl -d "/Users/klemonlab/Desktop/THT/THT_NACH/NACH_gbk_20" -n 8 -t 20 -C 99 -G -S 99 -e`

**Comment by brunocontrerasmoreira** [comment]
At this point I guess you should inspect the pangenome matrix to see whether it is always the same genome that has values > 1 in all clusters, or whether all genomes behave like that
