### ISSUE TITLE
Error in Get_homologues analysis

### ISSUE THREAD

**Issue by Utk92** [eead-csic-compbio/get_homologues#110]
I am running Get_homologues (https://github.com/eead-csic-compbio/get_homologues) on more than 230 genomes and getting zero clusters in between few genomes during the analysis.The net result is therefore zero clusters of homologues in the entire analysis.

However, when these zero cluster genomes are run separately the analysis provides adequate core genes among the genomes.Please help to resolve this error.

Let me know if any other information is required.
![Screenshot from 2023-10-07 14-24-45](https://github.com/eead-csic-compbio/get_homologues/assets/147254209/f4bd78d1-5954-4508-861f-9a919959e17b)
![Screenshot from 2023-10-07 14-24-18](https://github.com/eead-csic-compbio/get_homologues/assets/147254209/bd95a9ca-76a3-4cf4-bfe0-a357b0815229)

**Comment by eead-csic-compbio** [comment]
Hi @Utk92 , my guess would be that some of the BLAST jobs in the first run produced some output but failed to complete. This means that some of the *.blast.gz files will be smaller that the rest and you might want to remove them and re-run,
hope this helps,
Bruno
