### ISSUE TITLE
Could not solve for environment specs

### ISSUE THREAD

**Issue by iamaizhan** [eead-csic-compbio/get_homologues#112]
Hello, 

I have a problem with:

get_homologues % conda create -n get_homologues -c conda-forge -c bioconda get_homologues

Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides cogtriangles needed by get_homologues-3.5.4-hdfd78af_0

Could not solve for environment specs
The following package could not be installed
└─ get_homologues is not installable because it requires
   └─ cogtriangles, which does not exist (perhaps a missing channel).

   
Can you help me to solve this issue?
Thank you in advance!

**Comment by eead-csic-compbio** [comment]
I won't be able to test it for a couple days, but I will post this here in case this helps:
https://bioconda.github.io/recipes/cogtriangles/README.html#package-cogtriangles

**Comment by eead-csic-compbio** [comment]
Hi @iamaizhan , using conda 23.1.0 I succeeded in running these steps:

    conda activate bioconda 
    conda create -n get_homologues -c conda-forge -c bioconda get_homologues
    conda activate get_homologues

Please see https://bioconda.github.io in case you don't have bioconda installed,
Bruno
