### ISSUE TITLE
HOWTOTettelin is not found

### ISSUE THREAD

**Issue by jjv5** [eead-csic-compbio/get_homologues#117]
The manual describes a test script: HOWTOTettelin  to exercise the get_homologues.pl script. Where can this file be found?

**Comment by eead-csic-compbio** [comment]
Thanks for reporting @jjv5 , I will fix this tomorrow if that's ok,
Bruno

**Comment by eead-csic-compbio** [comment]
Good morning @jjv5, 
please git pull or download the latest release to get the updated software, it will take a little longer to propagate to conda.
The script [HOWTOTettelin.txt](https://github.com/eead-csic-compbio/get_homologues/blob/master/HOWTOTettelin.txt) and the folder [test_Streptococcus](https://github.com/eead-csic-compbio/get_homologues/tree/master/test_Streptococcus) have now been added to the repo, and the manual updated.
We appreciate your feedback,
Bruno
