### ISSUE TITLE
RefSeq vs GenBank

### ISSUE THREAD

**Issue by michalisgGk** [eead-csic-compbio/get_homologues#119]
Hello, 

is there a difference in using RefSeq files instead of GenBank files?

thanks in advance,
Michalis

**Comment by vinuesa** [comment]
Hi Michalis, you can use GenBank files (genome annotations in GenBank format) from the RefSeq or GenBank divisions. The main difference is that the genome assemblies stored in the RefSeq division satisfy specific quality criteria and are annotated with the PGAP (prokaryotic genome annotation pipeline), resulting in consistent annotations. Assemblies in the GenBank division have a much higher heterogeneity in the quality of the genomes and annotations. For pangenome analysis, I would strongly suggest using only RefSeq genomes. Cheers.

**Comment by michalisgGk** [comment]
Thank you for your answer!
I was confused because I didn't know that files from both divisions (RefSeq and GenBank) were called Genbank files, and I thought that the tool worked better with Genbank files from the Genbank division for some reason. Thank you for your suggestion as well, I was going to use RefSeq as you suggested, that is why I wanted to know if the tool works the same with these files as well.
