### ISSUE TITLE
parse_pangenome_matrix.pl

### ISSUE THREAD

**Issue by MostafaYA** [eead-csic-compbio/get_homologues#12]
Hi, 

I came across your nice tool `parse_pangenome_matrix.pl` which is to identify genes present in gp A absent  in B. We can skip singletons using `-S` to avoid sequences found in <2 taxa.
My question is: 
What if we want to calculate only the most common genes (>50%) in group A not in B. Could the `-S` default value be adjusted?

Thanks a lot,

**Comment by eead-csic-compbio** [comment]
Hi Mostafa, I have modified the -S option so that now it takes an integer which you can set to, for instance, half the number of input genomes. Please do git pull and try it out,
Bruno
