### ISSUE TITLE
redirect output to mounted volume

### ISSUE THREAD

**Issue by davidwcleary** [eead-csic-compbio/get_homologues#13]
Hi, 

I'm running get_homologues.pl from a 8 CPU 64GB RAM ubuntu instance and trying to redirect the output to a 2TB mounted volume (because the local 120GB is filling up).  My issue is that I tried to use -o to redirect the output but it is still using the local disk rather than the mounted volume.  The command I used is below. I realise this is almost certainly my issue (is what I am attempting to do even possible?) but if you have any suggestions that would be amazing. 

> sudo nohup /home/ubuntu/ghomol/get_homologues-x86_64-20170609/get_homologues.pl -d /dev/cog_data/genbank/ -c -R 1234 -m local -n 16 -M -X -z -t 0 -A -g -o /dev/cog_data/genbank_homologues/ &

Thanks so much in advance.
D

**Comment by eead-csic-compbio** [comment]
Hi David,
option -o is used to stop the program after the BLAST (and Pfam) scans are completed, so your command is not going to work.
Now, if you want to read in sequences at /path/genbank/ and save the results in a different partition, say /mount/volume/, you can do:

$ cd /mount/volume/
$  /home/ubuntu/ghomol/get_homologues-x86_64-20170609/get_homologues.pl -d /path/genbank -c -m local -n 16 -M -X -z -t 0 -A -g  

This way the output folder will be produced at /mount/volume and you won't fill your local partition,
hope this helps,
Bruno

**Comment by davidwcleary** [comment]
Hi Bruno, 
That is great, thanks very much (been looking forward to making use of get_homologues for ages!) and sorry for such a dumb question!
David
