### ISSUE TITLE
stuck on WARNING: please remove/rename results directory

### ISSUE THREAD

**Issue by Guella** [eead-csic-compbio/get_homologues#17]
so i ran 
./get_homologues.pl 
with this parameters -t 0 -M -n 16
and its always this message:

# 192 genomes, 1030166 sequences

# taxa considered = 192 sequences = 1030166 residues = 331534637 MIN_BITSCORE_SIM = 21.6

# mask=GCF000598065_f0_0taxa_algOMCL_e0_ (_algOMCL)

# skipped genome parsing (Genomas_Teste_2_homologues/tmp/selected.genomes)

# skip BLAST searches and parsing

# WARNING: please remove/rename results directory:
# '/mnt/e/Downloads/get_homologues-x86_64-20170609/Genomas_Teste_2_homologues/'
# if you change the sequences in your .gbk/.faa files or want to re-run

I haven't changed any sequence or any file on my source directory, any help?

**Comment by eead-csic-compbio** [comment]
Hi,
most likely that message appears when one or more genomes were removed from Genomas_Teste_2/ before re-running the script, is that your case?
If you want to repeat the analyses with less genomes you should use a -I list as explained in the manual. Directly removing genomes is not supported, hope this helps, Bruno
