### ISSUE TITLE
Problem with file naming (?)

### ISSUE THREAD

**Issue by cdeai** [eead-csic-compbio/get_homologues#18]
I made a successful GET_HOMOLOGUES analysis of cca. 60 proteomes (each in its own file). However, when I want to do the same analysis on a subset containing cca. 50 of these proteomes (with -I), I get 0 clusters. If I use it on a smaller subset (10 proteomes) the results seem to be ok.

If I do pangenome analyses on the same subset, I get a result, but some proteomes are missing in the final output.

What I notice is that there are strange pairings of the genomes in the screen output - see below marked in bold. When blast results are processed, proteomes 1, 2, 3, and 4 are added several times. The proteomes in pairs with them (e.g. 11, 22, 31, 33) are then missing from the pangenome results. I don't know if this could be the problem. If I remove proteomes 1, 2, 3 and 4 from the list, the strange pairs are still there.
Am I breaking some file naming rules and if this is the case, is it possible to avoid the problem without re-running the whole analysis from start (which takes a very long time)?

perl ~/Path/get_homologues-x86_64-20170807/get_homologues.pl -d input/ -r 10.faa -c -n 8 -I ListName.list

# included input files (51):
: 10.faa 10.faa 10704
: **1.faa 11.faa** 10637
: 12.faa 12.faa 10771
: 13.faa 13.faa 10513
: 14.faa 14.faa 10890
: 15.faa 15.faa 10577
: 16.faa 16.faa 10573
: 17.faa 17.faa 10668
: 18.faa 18.faa 10550
: 19.faa 19.faa 10775
: 20.faa 20.faa 10561
: **2.faa 22.faa** 10589
: 23.faa 23.faa 10858
: 24.faa 24.faa 10660
: 25.faa 25.faa 10597
: 26.faa 26.faa 10445
: 27.faa 27.faa 10643
: 28.faa 28.faa 10770
: 29.faa 29.faa 10887
: 30.faa 30.faa 10511
: **1.faa 31.faa** 10489
: **3.faa 33.faa** 10752
: 34.faa 34.faa 10889
: 35.faa 35.faa 10506
: 36.faa 36.faa 10788
: 37.faa 37.faa 10798
: 38.faa 38.faa 10650
: 40.faa 40.faa 10625
: **2.faa 42.faa** 10719
: **3.faa 43.faa** 10577
: **4.faa 44.faa** 10723
: 45.faa 45.faa 10537
: 46.faa 46.faa 10777
: 47.faa 47.faa 10827
: 48.faa 48.faa 10613
: 49.faa 49.faa 10817
: 50.faa 50.faa 9779
: **1.faa 51.faa** 10513
: **2.faa 52.faa** 10615
: **3.faa 53.faa** 10689
: **4.faa 54.faa** 10774
: 1.faa 1.faa 10778
: 2.faa 2.faa 10822
: 3.faa 3.faa 11081
: 4.faa 4.faa 10726
: 5.faa 5.faa 10558
: 6.faa 6.faa 10722
: 7.faa 7.faa 10589
: 8.faa 8.faa 9527
: 9.faa 9.faa 10484

**Comment by eead-csic-compbio** [comment]
Thanks for reporting this bug. I just posted a fix which in my tests sorts this out for get_homologues.pl and get_homologues-est.pl. It is included in release 20170918 (v3.0.8). Let me know if you still have problems with this, Bruno

**Comment by cdeai** [comment]
I re-ran the analysis overnight and everything seems to be working now. Perfect!
Thank you very much for the quick help!!
