### ISSUE TITLE
Error running COGS

### ISSUE THREAD

**Issue by Guella** [eead-csic-compbio/get_homologues#19]
so i got this while running COGs, what could it be?

# creating taxa indexes...
# construct_taxa_indexes: number of taxa found = 192

# clustering orthologous sequences
# checking lineage-specific expansions
# making COGs
# prunning COGs
# done

# add_unmatched_singletons : 2010 sequences, 185 taxa

# looking for valid ORF clusters (n_of_taxa=0)...

# EXIT : cannot create /mnt/e/Downloads/get_homologues-x86_64-20170609/Genomas_Teste_2_homologues/GCF000598065_f0_0taxa_algCOG_e0_/800310_endo-alpha--1->5--L-...faa

**Comment by eead-csic-compbio** [comment]
Hi Guella,
this seems to be caused by char ">", which is not a good idea in a file name. I will review the code now to sort this out, Bruno

**Comment by eead-csic-compbio** [comment]
I just submitted a fix, you would have to do git pull to update, Bruno

**Comment by Guella** [comment]
it worked! thanks!
