### ISSUE TITLE
get_homologues-est on one input file

### ISSUE THREAD

**Issue by cpaight** [eead-csic-compbio/get_homologues#21]
I am interested in using get_homologues-est, but I have a question about how the program would deal with one input fasta. I have RNA and DNA data from a multiple species in the same genus all in the same file. Would get_homologues-est be able to cluster a single input into orthologs? I apologize if this is a dumb question.

**Comment by eead-csic-compbio** [comment]
Hi, you would have to create one nucleotide FASTA file per species and put them all together in the same folder. Of course if you don't know to which species each sequence belong to this software won't help you. Hope this is useful for you, Bruno
