### ISSUE TITLE
issue drawing PNG images

### ISSUE THREAD

**Issue by jbadomics** [eead-csic-compbio/get_homologues#22]
Posting this here in case anyone runs into a similar issue. I'm running get_homologues on CentOS 6.9. R installed via linuxbrew with `brew install -s r --without-x11`. However, calling `plot_pancore_matrix.pl` kept returning this error:

```
# using default colors, defined in %COLORS

# globals controlling R plots: $YLIMRATIO=1.2
Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  : 
  unable to start device PNG
Calls: png
In addition: Warning message:
In png(file = "sample_intersection/pangenome_matrix_t0__shell.png") :
  unable to open connection to X11 display ''
Execution halted
```

Apparently R is trying to use X11 even though R was deliberately built without X11 support.

Fortunately, [this post](https://github.com/IRkernel/IRkernel/issues/388#issuecomment-237080809) fixed things for me. I added the following to my `~/.Rprofile`:

```
## Set default 'type' for png() calls - useful when X11 device is not available!
## NOTE: Needs 'cairo' capability
options(bitmapType='cairo')
```

**Comment by eead-csic-compbio** [comment]
Thanks for the tip, Bruno
