### ISSUE TITLE
hcluster_matrix.sh error

### ISSUE THREAD

**Issue by aupadrasta** [eead-csic-compbio/get_homologues#23]
Hi there,

I was getting an error while running the hcluster_matrix.sh giving Avg_identity.tab as an input.
Error is given below

Error in hclust(my_dist, method = "ward.D2") : 
  NA/NaN/Inf in foreign function call (arg 11)
Calls: as.phylo -> identical -> hclust
Execution halted
>>> ERROR: File hclust_gower-ward.D2_FperidonATCC33693PP4_f0_0taxa_algOMCL_e0_Avg_identity_tree.svg was were NOT generated!
>>> File gower_dist_matrix.tab was generated
>>> ERROR: File hclust_gower-ward.D2_FperidonATCC33693PP4_f0_0taxa_algOMCL_e0_Avg_identity_heatmap.svg was were NOT generated!
>>> ERROR: File hclust_gower-ward.D2_FperidonATCC33693PP4_f0_0taxa_algOMCL_e0_Avg_identity_tree.ph was were NOT generated!

Please suggest any modifications
Thanks
Aditya

**Comment by eead-csic-compbio** [comment]
Hi Aditya, can you please provide your ANI matrix, with annonymized labels if you prefer?
Bruno

**Comment by aupadrasta** [comment]
[FperidonATCC33693PP4_f0_0taxa_algOMCL_e0_Avg_identity.tab.zip](https://github.com/eead-csic-compbio/get_homologues/files/1679534/FperidonATCC33693PP4_f0_0taxa_algOMCL_e0_Avg_identity.tab.zip)

I have updated the software. now its giving an error 
Error in library(dendextend) : there is no package called 'dendextend'
Calls: suppressPackageStartupMessages -> withCallingHandlers -> library
Execution halted
>>> ERROR: File hclust_gower-ward.D2_FperidonATCC33693PP4_f0_0taxa_algOMCL_e0_Avg_identity_tree.pdf was  NOT generated!
>>> File gower_dist_matrix.tab was generated
>>> ERROR: File hclust_gower-ward.D2_FperidonATCC33693PP4_f0_0taxa_algOMCL_e0_Avg_identity_heatmap.pdf was NOT generated!
>>> ERROR: File hclust_gower-ward.D2_FperidonATCC33693PP4_f0_0taxa_algOMCL_e0_Avg_identity_tree.ph was NOT generated!
>>> File  was generated
>>> File  was generated

**Comment by eead-csic-compbio** [comment]
Can you please share the command line you used? After updating I guess now you're using hcluster_pangenome_matrix, right? This script was just updated so you might have found the first bug of this version. Pablo and I will look into it in the next 1-2 days, ok? Thanks for the report, Bruno

**Comment by aupadrasta** [comment]
Yes
I have used the
hcluster_pangenome_matrix.sh -i <input file>
Which i have sent to you

**Comment by eead-csic-compbio** [comment]
Hi,
I just had a quick check and it seems that your ANI matrix contains a lot of NA cells, which are most likely causing this error. Is this because this ANI was obtained from a set of genomes with core size = 0?

**Comment by aupadrasta** [comment]
Yes, the core size = 0. I have just rechecked it to confirm. 
There should be at least >20% identity among all the sequences which were subjected to analysis. I have no clue why its giving as NA??

**Comment by eead-csic-compbio** [comment]
Hi again,
well, those are pretty low identities, well into the twilight zone. 
Please note that coverage is probably the most important parameter and you may have to relaxed to recover those BLAST hits. Finally, even if BLAST gets them it does not mean that they will be called orthologues. 
Take home message: you need a core genome set of genes to compute ANI

**Comment by aupadrasta** [comment]
Dear Bruno,
Would you suggest any other way to do the analysis? or any changes to be made to run the scripts?
Thanks
Aditya

**Comment by eead-csic-compbio** [comment]
You have several options:
1) remove poor assemblies which might be missing core genes
2) remove species which are too distant to your genomes of interest
3) use get_homologues.pl -C 50 or even lower as remote homologues seem to display lower align coverage than close sequences

**Comment by vinuesa** [comment]
Hi Aditya, there are two problems:
1. The absolutely critical one is that all your rows contains NAs. R cannot proceed with such a matrix. As suggested by Bruno, try to relax the coverage parameter (leave it at -C 0). There is nothing to compute if the core size = 0. Another option is to compute the Avg_identity (ANI matrix) using the pan-genome instead.

2. You will also need to install the dendextend package, a new requirement of version 1.0.* of plot_matrix_heatmap.sh

Please let us know if we can further assist you with these matters.

**Comment by vinuesa** [comment]
Just added the complete.cases(tab)check, at the head of the script to stop its execution if( dim(tab)[1] < 3 ), as in your case.
