### ISSUE TITLE
[Question] Is it possible to exclude a taxon from get_homologs.pl when running compare_clusters.pl?

### ISSUE THREAD

**Issue by hydrahamster** [eead-csic-compbio/get_homologues#24]
Hi there,

For the initial script get_homologs.pl I included a taxon that I would like to leave out of the downstream analysis for the core, shell & pan transcriptome analysis. Re-running the get_homologs.pl would take close to a week. Is it possible to exclude a taxon in compare_clusters.pl?

Here are the flags I am currently using for the scripts:
`get_homologues.pl -M -t 0 -d .`
then
`compare_clusters.pl -o Genus-OMCL_intersection -m -d ._homologues/path-to-dir`

Thanks,

Liza

**Comment by eead-csic-compbio** [comment]
Hi,
there are two options with the current code:
i) Repeat get_homologues.pl -d data but adding option -I where the names of the input files/genomes of interest are included, one per line. This will take advantage of previously computed BLAST and homology results, so it would be a lot faster than te previos job, ok?
ii) Do compare_clusters.pl -I with a list of taxa of interest, but note that only single-copy clusters will be retrieved. This is usually what you want for phylogenies, but might not be appropriate for other uses.

Let me know if any of these are good enough or whether we should code a new flag for compare_clusters to fit your needs,
Bruno

**Comment by hydrahamster** [comment]
Hi Bruno,

Thanks for the swift reply! I'm trying to get option i) working, where the get_hom script re-runs with the previous BLAST results. I think I am getting the syntax wrong and every combination I've tried comes up in an error. Could you have a look at what I might be doing wrong please?

command: `get_homologues.pl -M -t 0 -d . -I transcriptome1.faa,transcriptome2.faa,transcriptome3.faa`

I've copied the `._homologues` folder into that directory, as well as the transcriptome files that were used for the initial run, minus the one outgroup that I want to exclude. The error I'm getting is this:
`# EXIT : cannot find previous input file transcriptome4.faa, please re-run everything`

Should I be using other file names, an output in the `._homologues` folder or something, for the `-I` flag rather than the initial fasta files?

Cheers,
Liza

**Comment by eead-csic-compbio** [comment]
Hi Liza,
you should put those fasta filenames, one per line, in a text file and the call the program with the same -d folder but adding -I file.text. You should see that the programs first reads all input sequences but then analyzes only those included in -I

**Comment by hydrahamster** [comment]
Hi Bruno,

Thanks for clarifying that for me. Job is running now.

All the best,
Liza
