### ISSUE TITLE
COG pan-transcriptome from single file

### ISSUE THREAD

**Issue by hydrahamster** [eead-csic-compbio/get_homologues#25]
Hi there,

Trying to run get_homologues pan transciptome analysis from a single file. Just fine for OMCL, but the COG algorithm is coming up with the error  `# EXIT: need at least three taxa to run COGtriangles algorithm`

There are five taxa, but the input is a single file. taxa are identified by `[genus species]` in the amino acid fasta header.
command called with `./get_homologues.pl -G -t 0 -i allAA_transdec_cd-hit_cluster-out.fasta`

Am I doing something wrong or is there a trick to calling the COG pan-tran from a single file over the OMCL one?

**Comment by eead-csic-compbio** [comment]
Hi, you might have found a bug, but just in case, can you post examples of your FASTA headers so that I can rule out a formatting issue? 
Cheers, Bruno

**Comment by hydrahamster** [comment]
HI Bruno,

Sure thing, here is the first AA seq from the input file (the rest of the file is the same format):

>UTSMER9A3_Gambierdiscus-carpenteri_DN10000_c0_g1_i1.p1 [Gambierdiscus carpenteri]
VVVGVSSRLVQNVWSGLGNITEICLDTTKGQHFIIVKSIGTPRHADDFEEQRDHASYFTEAAFYEKGYAEKLLAAGALCPKPLLVDRATDGSLHICMTKLSGWSCAGGADRAQAFAALSWLARLHALFWGSSRADKAVLHGLQKQGCYWNLDSRQLELARTPEEGLEGRLRRSASVVDARLKEDLLQTICHGDPKDSNMICSIDGCLGFCDFQWTGKAPCSKDLAYCIICGIDRLTLEDELRYLSHYHSELVRLLEYQGDA
>UTSMER9A3_Gambierdiscus-carpenteri_DN10000_c0_g1_i2.p1 [Gambierdiscus carpenteri]
VVVGVSSRLVQNVWSGLGNITEICLDTTKGQHFIIVKSIGTPRHADDFEEQRDHASYFTEAAFYEKGYAEKLLAAGALCPKPLLVDRATDGSLHICMTKLSGWSCAGGADRAQAFAALSWLARLHALFWGSSRADKAVLHGLQKQGCYWNLDSRQLELARTPEEGPWLMPGLRRTCCRQFATVTRRIPT*

**Comment by eead-csic-compbio** [comment]
OK, but you mention 5 species, so you have other sequences in the same FASTA file with different [scientific names], right?

**Comment by hydrahamster** [comment]
The answer was going to be a resounding yes, but I think something went wrong with my script. Thank you for your swift response Bruno and I'm going to have a look what just happened there.

**Comment by hydrahamster** [comment]
Hi Bruno,

Fixed the problem on my end. COG is running just fine from a single file. My apologies for that and again thank you for your super swift response!

Cheers,

Liza
