### ISSUE TITLE
compare_cluster.pl fail to extract fasta headers?

### ISSUE THREAD

**Issue by indexofire** [eead-csic-compbio/get_homologues#26]
Something wierd after running get_homologues.pl for gbk files(sample_plasmids_gbk and my gbk data all get this errors), compare_cluster.pl was run to get cluster of genes. But some errors showed like this: 

**errors in v 3.0.8**

```
...
Argument "" isn't numeric in numeric comparison (<=>) at ./compare_clusters.pl line 619.
...

```

**errors in 3.1.2.**

```
...
Use of uninitialized value in hash element at ./compare_clusters.pl line 300.
...
Argument "" isn't numeric in numeric comparison (<=>) at ./compare_clusters.pl line 627.
...
```

And the *_t0.tab file contained few gene distribution, which will get error msg by running plot_matrix_heatmap.sh. 

two different versions were tried, but kind of same errors were displayed. Need help! thanks.

**Comment by eead-csic-compbio** [comment]
Hi, thanks for reporting this.
I haven't been able to reproduce this with sample_plasmids_gbk, can you please post here your exact commands? Cheers, Bruno
