### ISSUE TITLE
feature-add HipMCL as one of the clustering options

### ISSUE THREAD

**Issue by zymergen-sgordon** [eead-csic-compbio/get_homologues#27]
Bruno, can you add HipMCL as one of the clustering options?

**Comment by eead-csic-compbio** [comment]
Hi Sean, we are looking into it. In a couple of tests in a standard Linux server I have seen a 25% performance gain (in real time compared to multithreaded MCL). However, the formats are not the same and I haven't been able to find the right params to reproduce the results of the original MCL (we have reached out to the authors and they are helping out). Furthermore, the compilation requires mpich. So we might add it as an option but relying on user's binaries to keep things simple, Bruno

**Comment by zymergen-sgordon** [comment]
Thanks!  I guess speed up will also depend on size of the dataset.  So its
more relevant for large datasets that I have in mind.

Best,

Sean
