### ISSUE TITLE
POCP values greater than 100

### ISSUE THREAD

**Issue by ATVincent** [eead-csic-compbio/get_homologues#28]
Hello,

I just tested the "-P" option of the latest version of GET_HOMOLOGUES to calculate the values of POCP. I sometimes have values over 100. How is this possible?

Thank you

**Comment by eead-csic-compbio** [comment]
Hi, thanks a lot for the bug report. 
I have just committed a new version to the repository. Can you please git pull and try it again? 
It was not counting correctly the number of sequences of the same taxon in each cluster, but I believe I fixed it now. Please let me know if there's still something wrong, Bruno

**Comment by ATVincent** [comment]
Hello,

Thank you for this quick response. Indeed, the problem seems fixed (thank you). Do you believe that you will be making a new official release soon? I would like to be able to cite the correct version of GET_HOMOLOGUES in my upcoming papers.

Truly,

Antony

**Comment by eead-csic-compbio** [comment]
Hi Antony,
you can cite version 06062018, please let us know how your tests go in case some more tweaks are required, this is work in progress, Bruno
