### ISSUE TITLE
strains missing in final output

### ISSUE THREAD

**Issue by alexweisberg** [eead-csic-compbio/get_homologues#31]
I ran get_homologues version "24052018" with diamond searches and MCL clustering, as well as compare_clusters.pl and parse_pangenome_matrix.pl. The analysis ran to completion, however two of my strains are missing from the pangenome matrix as well as the individual cluster files.

These strain files were named "2.gbk" and "4.gbk", which sounds like a similar problem as another user, however I also have input files such as 24.gbk and 17.gbk that were correctly included. These annotated assemblies were assembled at the same time using the same pipeline. It looks like something is failing during the "identifying orthologs" step.

Here is a portion of the screen output:

> /home/Software/get_homologues-x86_64-20180524/get_homologues.pl`
>
> -i 0 -d ./genomesfull -o 0 -X 1 -e 0 -f 0 -r USDA110.gbk -t 0 -c 0 -z 0 -I 0 -m local -n 1 -M 1 -G 0 -p >0 -C 75 -S 1 -E 1e-05 -F 1.5 -N 0 -B 50 -b 0 -s 0 -D 0 -g 0 -a '0' -x 0 -R 0 -A 0 -P 0
>
> version 24052018
> results_directory=/home/Data/genomesfull_homologues
> parameters: MAXEVALUEBLASTSEARCH=0.01 MAXPFAMSEQS=250 BATCHSIZE=100 >KEEPSCNDHSPS=1
> diamond job:1
>
> checking input files...
>...
> 17.gbk 7929
> 2.gbk 9953
> 21.gbk 6625
> 23.gbk 8320
> 24.gbk 9336
> 38B.gbk 8065
> 4.gbk 7658
> 48-1.gbk 8860
> 62-1.gbk 6921
>...
> identifying orthologs between otherstrain.gbk and 2.gbk (0)
> 0 sequences
>
> identifying orthologs between otherstrain.gbk and 21.gbk (0)
> 5145 sequences
>
> identifying orthologs between otherstrain.gbk and 23.gbk (0)
> 5279 sequences
>
> identifying orthologs between otherstrain.gbk and 24.gbk (0)
> 4467 sequences
>
> identifying orthologs between otherstrain.gbk and 38B.gbk (0)
> 5240 sequences
>
> identifying orthologs between otherstrain.gbk and 4.gbk (0)
> 0 sequences
>...
> occupancy stats:
 >  cloud  shell  soft_core  core
>17.gbk 48 4204   2683   284
>21.gbk 26 3292   2678   284
>23.gbk 82 4385   2548   284
>24.gbk 88 3434   1971   284
>38B.gbk 77 3977   2681   284
>48-1.gbk   83 4723   2683   284
>62-1.gbk   36 3515   2648   284
>...etc

**Comment by eead-csic-compbio** [comment]
Please check that those strains appear in cluster_list file, i am away until monday, sorry, Bruno

**Comment by alexweisberg** [comment]
Hi, thank you. Those strains do not show up in the cluster_list file, but they do show up in the input_order.txt file. Every strain except for those named 2.gbk and 4.gbk show up in cluster_list.

**Comment by eead-csic-compbio** [comment]
Please send those two gbk files plus a couple more so that we can reproduce the error, cheers

**Comment by alexweisberg** [comment]
Here is a tar file with several genomes from the analysis. Each of them should work except for 2.gbk and 4.gbk. Thanks!
https://drive.google.com/open?id=1Ddrm-yHshE6aTGK53ZHXcvlCYxjNbOjv

**Comment by eead-csic-compbio** [comment]
Hi Alex, sorry for the delay.
I downloaded your files trying to reproduce your error and run the following command:
$ get_homologues.pl -d test -t 0 -m local -n 20 -M

After completion I did 
$ head  test_homologues/Bsp_f0_0taxa_algOMCL_e0_.cluster_list

cluster 1_hypothetical_protein size=2 taxa=2 file: 1_hypothetical_protein.faa dnafile: 1_hypothetical_protein.fna
: 09LoS36_1.gbk
: 17.gbk
cluster 2_hypothetical_protein size=6 taxa=5 file: 2_hypothetical_protein.faa dnafile: 2_hypothetical_protein.fna
: 09LoS36_1.gbk
: 17.gbk
: 17.gbk
: 2.gbk
: 4.gbk
: B_sp._Rc3b.gbk

So it looks like strain 2.gbk really does appear in the cluster_list file. I am not sure what the problem is,
Bruno

**Comment by eead-csic-compbio** [comment]
This is what I did:

$ get_homologues.pl -d test -t 0 -m local -n 20 -M

$ compare_clusters.pl -d test_homologues/Bsp_f0_0taxa_algOMCL_e0_ -o clusters -m

$ perl -F'\t' -ane '$r++;for(1 .. @F){$m[$r][$_]=$F[$_-1]};$mx=@F;END{for(1 .. $mx){for $t(1 .. $r){print"$m[$t][$_]\t"}print"\n"}}'    clusters/pangenome_matrix_t0.tab > clusters/pangenome_matrix_t0.tr.tab

$ head clusters/pangenome_matrix_t0.tr.tab
source:/home/contrera/Descargas/clusters	09LoS36_1.gbk	17.gbk	2.gbk	4.gbk	B_pachyrhiziBR3262.gbk	B_sp._Rc3b.gbk	B_sp._Y36.gbk	
1_hypothetical_protein.faa	1	1	0	0	0	0	0	
2_hypothetical_protein.faa	1	2	1	1	0	1	0	
3_hypothetical_protein.faa	1	1	0	0	0	0	0	
4_hypothetical_protein.faa	1	1	0	0	0	0	0	
5_hypothetical_protein.faa	3	2	1	1	0	0	0	
6_Blue-light-activated...faa	1	1	0	0	0	0	0	
7_hypothetical_protein.faa	1	1	0	0	0	0	0	
9_hypothetical_protein.faa	1	1	0	0	0	0	0	
10_FecR_protein.faa	1	1	1	0	1	1	0	

In this data set I can 2.gbk in all output files,
Bruno

**Comment by alexweisberg** [comment]
Hi Bruno,

Thank you for looking into this. I will also rerun some test runs with these specific genomes on our machine and double check the output to make sure it matches yours. I also realized another genome (with a more unique name and not just a number) is also missing, so I think something else is going on.

Alex

**Comment by alexweisberg** [comment]
I believe I have identified what is going on. When a strain filename is a postfix subset of another genomes file name, one of them is excluded from the analysis. For example, the files "B_sp_WSM2.gbk" and "2.gbk" results in 2.gbk having 0 orthologs. When I add another copy of 2.gbk but rename it as inoc2.gbk, inoc2.gbk is correctly included. This also happened for genomes named "B_sp._LTSP857.gbk" and "LTSP857.gbk", which was accidentally included and also resulted in 0 orthologs. This was run with version 20180524.

**Comment by eead-csic-compbio** [comment]
Hello again Alex,
today I realised that your original error report was using DIAMOND (-X) so I re-tested everything with -X. I haven't seen any problem with genome name prefixes but found that when a new genome is added to the pool in DIAMOND analyses there was a bug. In particular, DIAMOND result of one genome vs the rest were not re-computed and this caused downstream problems. I have just submitted a new release (20180828) with this fixed.
Can you remember if you added some genomes later? If this is the case please remove your *others.blast* files and please re-run. Let us know if that fixes your error,
Bruno

**Comment by alexweisberg** [comment]
Hi Bruno,

Thank you, yes the dataset is one where additional genomes were added later. I will try the new version after removing that file and will let you know if it works.

Alex
