### ISSUE TITLE
Please add some explanation about the outputs to the manual

### ISSUE THREAD

**Issue by soungalo** [eead-csic-compbio/get_homologues#33]
Hello,
I decided to give GET_HOMOLOGOUS_EST a try, so I ran the sample data as explained in the manual.
The output directory created contains the following files (among others):
```
pan_genome_algOMCL.tab
core_genome_algOMCL.tab
soft-core_genome_algOMCL.tab
Esterel_alltaxa_algOMCL_e0_.cluster_list
Esterel_alltaxa_algOMCL_e0_Avg_identity.tab
```
as well as the directory `Esterel_alltaxa_algOMCL_e0_`, containing more files.
However, I am failing to understand the contents/format of these output files, and I couldn't find an explanation anywhere in the documentation. It would be very useful to me (and probably other users) if you could add this to the manual, unless it is already documented somewhere (in which case please direct me to the relevant document).
For example:
```
$ cat sample_transcripts_fasta_est_homologues/pan_genome_algOMCL.tab
g1      g2      g3      g4
4665    8938    13004   27014
4665    9002    24277   26201
4665    21283   23347   25641
4665    8938    24058   26352
20013   22562   24637   26478
20013   22169   24583   26507
4665    21283   23697   25621
4838    9098    12961   26971
20013   22562   24565   26489
4838    9098    24345   26186
4755    9100    24347   26188
4755    9100    12963   26973
4755    21348   23761   25602
4755    8956    24076   26370
4838    9114    24389   26313
4665    9002    12931   26941
4755    8956    13022   27032
20013   22169   24233   26527
20013   22245   24658   26499
4838    21639   23714   25555
```
What are g1,g2,g3,g4? And what do the numbers represent?
Thanks!

**Comment by eead-csic-compbio** [comment]
Thanks for your message. I have now added section "Output files explained" to the EST manual with URL http://eead-csic-compbio.github.io/get_homologues/manual-est/manual-est.html#SECTION00057000000000000000

Let me know if you further questions, cheers,
Bruno

**Comment by soungalo** [comment]
Awesome! That clears things out.
