### ISSUE TITLE
compare_clusters.pl not producing .fasta file

### ISSUE THREAD

**Issue by morgansobol** [eead-csic-compbio/get_homologues#34]
Hi, 

I am trying to produce the binary alignment file so that I can feed it t IQ-Tree.
I ran the compare_clusters.pl script after running get_homologues, but the .fasta file was not produced. Only the .phylip, .tab, and cluster list were produced. 
Can you please help me figure out why this file was not produced?

My get_homologues script:
get_homologues.pl -d /work/Geomicrobiology/msobol/IODP_329_SPG/get_homologues/genomes/ -n 20 -M -t 18 -e

My compare_clusters script:
compare_clusters.pl -o compare_clusters -d /work/Geomicrobiology/msobol/IODP_329_SPG/get_homologues/genomes_homologues/Pdigitatumproteins_f0_18taxa_algOMCL_e1_/ -m

Thanks,
Morgan

**Comment by eead-csic-compbio** [comment]
Hi Morgan, can you please post the output of compare_clusters.pl?

**Comment by morgansobol** [comment]
Sorry forgot to post that. Please find the output below:

# /home/apps/get_homologues/20170609/compare_clusters.pl -d /work/Geomicrobiology/msobol/IODP_329_SPG/get_homologues/homologues/Pdigitatumproteins_f0_18taxa_algOMCL_e1_/ -o compare_clusters2 -n 0 $

# number of input cluster directories = 1

# parsing clusters in /work/Geomicrobiology/msobol/IODP_329_SPG/get_homologues/homologues/Pdigitatumproteins_f0_18taxa_algOMCL_e1_ ...
# cluster_list in place, will parse it (/work/Geomicrobiology/msobol/IODP_329_SPG/get_homologues/homologues/Pdigitatumproteins_f0_18taxa_algOMCL_e1_.cluster_list)
# number of clusters = 3

# intersection output directory: compare_clusters2
# intersection size = 3 clusters

# intersection list = compare_clusters2/intersection_t0.cluster_list

# pangenome_file = compare_clusters2/pangenome_matrix_t0.tab
# pangenome_phylip file = compare_clusters2/pangenome_matrix_t0.phylip

# WARNING: Venn diagrams are only available for 2 or 3 input cluster directories

**Comment by eead-csic-compbio** [comment]
Is it possible that you might be using an older version which did not produce FASTA yet? Can you check your get_homologues version please?

**Comment by morgansobol** [comment]
The get_homologues version is 23072018, but I used version 20170609 for compare_clusters.pl
Is this an issue? I switched the versions for compare_clusters.pl because the 23072018 version was giving me this error: /usr/bin/env: perl -w: Not a directory

**Comment by eead-csic-compbio** [comment]
It does matter because FASTA output was only added recenly.
So you should use the 2018 version. I haven't seen that error, but I guess you could get around it doing $ perl compare_clusters.pl ...

Let me know how it goes,
Bruno

**Comment by morgansobol** [comment]
Thank you that fix made compare_clusters.pl work. 
However, IQ-Tree did not work because the alignment has too many identical sequences. 
Would this be due to the fact that I did not set -t 0 within the get_homologues.pl script?
If I need to open another issue please let me know.
Thank you.

**Comment by eead-csic-compbio** [comment]
Yes you need -t 0 to get a pangenome matrix, cheers

**Comment by eead-csic-compbio** [comment]
There's a script for this kind of analyses at
https://github.com/vinuesa/get_phylomarkers
