### ISSUE TITLE
ERROR: failled generating all_ortho.mcl file (OMCL)

### ISSUE THREAD

**Issue by diaz13** [eead-csic-compbio/get_homologues#35]
hi
Get_homologues gives this error: 
ERROR: failed generating /home/user/Tools/get_homologues-master/faa_homologues/tmp/all_ortho.mcl file (OMCL).

I do not know the cause of this error ??

**Comment by eead-csic-compbio** [comment]
Hello,
first I would check whether $ perl get_homologues.pl -v
confirms that all binaries are in place, including EXE_MCL.
If that is correct then you should check that file /home/user/Tools/get_homologues-master/faa_homologues/tmp/all_ortho.mcl actually was created or not. Occasionally network/latency issues  might explain these errors, and they often can be sorted out by simply re-running your command,
cheers, Bruno

**Comment by diaz13** [comment]
Hello @eead-csic-compbio 
yes all is OK with the command perl get_homologues.pl -v, including EXE_MCL.
 /home/user/Tools/get_homologues-master/faa_homologues/tmp/all_ortho.mcl was created.
I rerun the command and I'll come back to you to tell if it's work or not.
Thanks
