### ISSUE TITLE
error running COGs

### ISSUE THREAD

**Issue by diaz13** [eead-csic-compbio/get_homologues#36]
I finish the get_homologs with mcl. But i run with COGS, he returns the following error:

 ERROR: find_COGs (/home/user/Tools/get_homologues-master//bin/COGsoft/COGtriangles/COGtriangles ) failed to terminate job.

I don't known why ??

**Comment by eead-csic-compbio** [comment]
Hi,
can you please re-run the same command without deleting any files? Sometimes this happens due simply to disk latency times, Bruno

**Comment by eead-csic-compbio** [comment]
I added #include <unistd.h> at bin/COGsoft/COGreadblast/bc.h and now it compiles fine. I am doing a new release, thanks for reporting it, Bruno

**Comment by diaz13** [comment]
the all modules is OK if i run get_homologues.pl -v including COG.

**Comment by eead-csic-compbio** [comment]
So it means your binary works anyway. Still it is not completing your analysis, umm. Of your data is not massive and you dont mind to share it, please share it so I can try to reproduce the error here, BRuno

**Comment by diaz13** [comment]
I have 330 genomes of a bacteria so I think they are massive.

**Comment by eead-csic-compbio** [comment]
Yes they are large. Let's try tow things:
1) compress your input genomes in a tgz file so that I can download them from a link provided by you in my email bcontreras at eead dot csic dot es 
2) please also send separately the cog outputfiles from your _homologues/tmp folder to see if they give us information, have you chekc that your disk is not full and stuff like that?

**Comment by eead-csic-compbio** [comment]
You should provide a link to dropbox, drive or similar

**Comment by diaz13** [comment]
Hello

I come back to you.
here is the error he gives me when I make?

root@vwalf6003:/home/user/Téléchargements/get_homologues-master/bin/COGsoft/COGr
eadblast# make
g++ -O2 -c reader.cpp
make: g++ : commande introuvable
Makefile:15 : la recette pour la cible « reader.o » a échouée
make: *** [reader.o] Erreur 127

**Comment by eead-csic-compbio** [comment]
Hi, it seems that you need to install the g++ compiler in your system? In Ubuntu that would be done with $ sudo apt-get install g++

**Comment by eead-csic-compbio** [comment]
In Redhat-derived distros you could do it with: 
$ yum -y install gcc-c++

**Comment by diaz13** [comment]
this command yum -y install gcc-c++ 
root@vwalf6003:/home/user/Tools/get_homologues-master/bin/COGsoft/COGreadblast# yum -y install gcc-c++
No deposit is activated.
  Run "yum repolist all" to see the list of installed repositories.
  You can enable repositories with the yum-config-manager command --enable <repo>

and i rerun make.

root@vwalf6003:/home/user/Tools/get_homologues-master/bin/COGsoft/COGreadblast# make
g++ -O2 -c bc.cpp
bc.cpp: In function ‘void myOpenDir(const char*)’:
bc.cpp:7:16: error: ‘chdir’ was not declared in this scope
   chdir(dirpath);
                ^
Makefile:18 : la recette pour la cible « bc.o » a échouée
make: *** [bc.o] Erreur 1

**Comment by eead-csic-compbio** [comment]
Thanks, source file bc.h was updated 13 days ago (https://github.com/eead-csic-compbio/get_homologues/releases/tag/v3.1) and that will fix this issue. Can you download the latest release?
Otherwise you can clone the repo with $ git clone 

Either way you could then run $ perl instal.pl

**Comment by diaz13** [comment]
Can't call method "id" on an undefined value at /var/www/cgi-bin/STEP/display_conserved_v9.cgi line 134.
thanks

**Comment by eead-csic-compbio** [comment]
Sorry, can you explain how you got this?

**Comment by diaz13** [comment]
sorry I made a mistake. I will re-do the installation with the new update. and I'll see if it works.
Thank you

**Comment by diaz13** [comment]
Hi 
I have the same problem
# checking lineage-specific expansions
# making COGs
# ERROR: find_COGs (/home/user/Tools/get_homologues-master//bin/COGsoft/COGtriangles/COGtriangles ) failed to terminate job

**Comment by eead-csic-compbio** [comment]
Hello again, 
can you please run perl install.pl and let me know how it goes? According to your previous messages it seems that our COG binaries don't work in your system so you will have to recompile them even with the new release. Hopefully you will now be able to accomplish compilation, please let me know, Bruno

**Comment by diaz13** [comment]
If i run perl install.pl, everything seems ok.

### 1) checking required parts: 

## checking whether source and binaries of dependencies are in place
>> OK

## checking mcl-14-137 (lib/phyTools: $ENV{'EXE_MCL'})
>> OK
## checking COGsoft/COGreadblast (lib/phyTools: $ENV{'EXE_READBLAST'})
>> OK
## checking COGsoft/COGtriangles (lib/phyTools: $ENV{'EXE_COGTRI'})
>> OK
## checking COGsoft/COGlse (lib/phyTools: $ENV{'EXE_COGLSE'})
>> OK
## checking COGsoft/COGmakehash (lib/phyTools: $ENV{'EXE_MAKEHASH'})
>> OK
## Checking blast (lib/phyTools: $ENV{'EXE_BLASTP'})
>> OK

### 2) checking optional parts: 


## checking optional HMMER binaries (lib/phyTools: $ENV{'EXE_HMMPFAM'})
# required by get_homologues.pl -D
>> OK
## checking optional PFAM library (lib/phyTools: $ENV{'PFAMDB'})
# required by get_homologues.pl -D and get_homologues-est.pl -D
# cannot locate Pfam-A, would you like to download it now? [Y/n]
n
<< You might manually download Pfam-A.hmm.gz from ftp.ebi.ac.uk/pub/databases/Pfam/current_release/ to any location
<< and edit variable PFAMDB as to point to that location, as explained in the manual.
<< Then re-run
## checking optional SWISSPROT library (lib/phyTools: $ENV{'BLASTXDB'})
# required by transcripts2cds.pl and transcripts2cdsCPP.pl
# cannot locate SWISSPROT, would you like to download it now? [Y/n]
n
<< You might manually download /home/user/get_homologues-master/db/uniprot_sprot.fasta.gz from ftp.uniprot.org//pub/databases/uniprot/current_release/knowledgebase/complete/ to any location
<< and edit variable BLASTXDB as to point to that location, as explained in the manual.
<< Then re-run
## checking optional software R (lib/phyTools: $ENV{'EXE_R'})
# required by compare_clusters.pl, parse_pangenome_matrix.pl -s, plot_pancore_matrix.pl and
# plot_matrix_heatmap.sh, hcluster_pangenome_matrix.sh
>> OK
## checking optional Perl module GD
# required by parse_pangenome_matrix.pl -p
>> OK

### 3) Your get_homologues kit is now fully functional

**Comment by eead-csic-compbio** [comment]
Hi, can you do this?

cd bin/COGsoft;
cd COGlse; make;
cd ../COGmakehash;make;
cd ../COGreadblast;make;
cd ../COGtriangles;make

**Comment by diaz13** [comment]
root@vwalf6003:/home/user/Documents/get_homologues-master/bin/COGsoft# cd COGlse/; make;
g++ -O2 -c mklse.cpp
g++ -O2 -c reader.cpp
g++ -O2 -o COGlse mklse.o reader.o
root@vwalf6003:/home/user/Documents/get_homologues-master/bin/COGsoft/COGlse# ../COGmakehash/; make;
bash: ../COGmakehash/ : est un dossier
make: « COGlse » is up to date.
root@vwalf6003:/home/user/Documents/get_homologues-master/bin/COGsoft/COGlse# ../COGreadblast/; make;
bash: ../COGreadblast/ : est un dossier
make: « COGlse » is up to date.
root@vwalf6003:/home/user/Documents/get_homologues-master/bin/COGsoft/COGlse# ../COGtriangles/; make;
bash: ../COGtriangles/ : est un dossier
make: « COGlse » is up to date.

**Comment by eead-csic-compbio** [comment]
So it seems your binaries are ok. Can you now check whether _homologues/tmp/COGtriangles.log files exists and its contents?

**Comment by brunocontrerasmoreira** [comment]
In that case I suggest you simply re-run the get_homs -G command, this could be a disk/network latency issue

**Comment by diaz13** [comment]
i can try this.
Thanks

**Comment by bioinformatist** [comment]
Dear @eead-csic-compbio and @brunocontrerasmoreira ,
I have exactly same problem with @diaz13 's.
The console send STDERR contents:

```pre
# ERROR: find_COGs (/home/ysun/get_homologues-x86_64-20190102//bin/COGsoft/COGtriangles/COGtriangles ) failed to terminate job
```

I'm sure that my COG binaries work well, and I've also got some logs:
[COGreadblast.log](https://github.com/eead-csic-compbio/get_homologues/files/2763954/COGreadblast.log)
[COGtriangles.log](https://github.com/eead-csic-compbio/get_homologues/files/2763955/COGtriangles.log)

My data is not massive but I'd like to not upload them here while giving you a procedure to reproduce it:
First you need a accession list file:
[geobacter_ref_list.txt](https://github.com/eead-csic-compbio/get_homologues/files/2763965/geobacter_ref_list.txt)
With this file, run the command like:

```shell
../get_homologues-x86_64-20190102/download_genomes_ncbi.pl geobacter_ref_list.txt
```

Then run `../get_homologues-x86_64-20190102/get_homologues.pl -d /home/ysun/evo -n 48 -G -X`.

You will get the same error with us. It will take only ~5min to reproduce this.

Thank you for your help.

**Comment by brunocontrerasmoreira** [comment]
Thanks for the list and the logs, I'll have a look and let you know, Bruno

**Comment by brunocontrerasmoreira** [comment]
Dear @bioinformatist , I successfully run your suggested commands with 11geobacter strains in two different Ubuntu versions and in a slightly older CentOS systems. You can see the results at
[COG.zip](https://github.com/eead-csic-compbio/get_homologues/files/2768031/COG.zip)

Therefore I guess this is related to this FAQ in the manual, which often is sorted by simply repeating the same command: 
"How does buffer flushing affects get_homologues.pl?
Although get_homologues.pl scripts explicitily flush output buffers (set with $|=1), users can occasionally experience buffering problems when writing to slow, external hard drives, as output files are often very large. Such problems have been reported when calling -G option, which in turn invokes subroutine find_COGs and calls several external binaries, whose buffers cannot be flushed from the scripts. If that happens to you please consider increasing the sleep time in that sub, which by default is 10 seconds. "

**Comment by bioinformatist** [comment]
Dear @brunocontrerasmoreira , I have tried [change the sleep time to 300 s](https://github.com/eead-csic-compbio/get_homologues/blob/0164165b46618f396d2f4ba56c600bf6cace9921/lib/marfil_homology.pm#L2767) or even longer time, but it fails again with same error.

I also try call `sync` to force the system write the buffer to disk once the sub-process finished, unfortunately, it still not works.

Actually, I'm not sure if it is caused by the program itself, for I noticed that file `query2subject.csv` in temp folder is empty.

And according to code, it seems that the exception is thrown by empty intermediate files `cog-edges.txt` and `all-edges.txt`.

Can you tell me what status/contents these files have?

Thanks for very quick reply!~

**Comment by eead-csic-compbio** [comment]
Those files are created by COGs, you can analyze the sample datasets to see how they look like.
It would be really useful if you could tell me a set of geobacter strains that cause this problem so I can reproduce it.

**Comment by bioinformatist** [comment]
Dear @eead-csic-compbio , just see the comment I replied 2 days ago, I provided an accession list of geobacter, you can use `download_genomes_ncbi.pl` and to reproduce this problem. But @brunocontrerasmoreira told me that he works well with this demo so I'm not sure which step turn to bad up to now.
I do use the latest version of the software.

**Comment by brunocontrerasmoreira** [comment]
Hello @bioinformatist , sorry for the username confusion. As I said 3 messages back, I was not able to reproduce your bug in three different systems using that list of geobacter strains. Did you run ./install.pl to check all your COG binaries?
