### ISSUE TITLE
Effect of BLAST parameter -max_target_seqs on GET_HOMOLOGUES 

### ISSUE THREAD

**Issue by eead-csic-compbio** [eead-csic-compbio/get_homologues#38]
Hi,
a recent paper reported that the usual way the parameter -max_target_seqs in BLAST jobs is used is impacting the correctness of bioinformatics workflows. You can read more about that at https://www.biostars.org/p/340129. The story is that users of this option expected to get the best N hits out of the total list of hits produced by BLAST, sorted by bitscore. However, current standalone BLAST binaries in fact return the first H hits found that meet the E-value cutoff.
What is the effect of this on GET_HOMOLOGUES jobs? Given that coverage is the main parameter controlling our BLAST jobs and that -max_target_seqs is set to the number of sequences in the proteome/genome being searched, this parameter cannot have any significant effect of the alignments reported, as in fact we set a large number of hits to ensure that all hits, even poor ones, are recovered.

Auxiliary script transcripts2CDS.pl does use a small value (5) for this parameter, but again I expect it to have littel effect on results as these BLASTX searches don't necessarily require the best hit as long as the correct Open Reading Frame in found.

Anyway, please report any problems you might observe, Bruno

**Comment by brunocontrerasmoreira** [comment]
This bug has been fixed in BLAST version 2.8.1+. Read more at https://doi.org/10.1093/bioinformatics/bty1026
