### ISSUE TITLE
pfam_enrich missing output?

### ISSUE THREAD

**Issue by korinalb** [eead-csic-compbio/get_homologues#39]
I'm running `pfam_enrich.pl` and it seems to be running fine but nothing shows up in the output. 

Below is what I get when as the output--I'm running this on a computing cluster and the following result is what was emailed to me. Does this script produce a .txt file that would include the list of enriched pfams, or do I really have no enriched pfams?

```
# /share/pkg/get_homologues/3.1.2/pfam_enrich.pl -d infantis_homologues -c infantis_homologues/UCD304_f0_0taxa_algOMCL_e0_ -x infantis_intersection/infpan/pangenome_matrix_t0__shell_list.txt -n 1 -s 0 -e 0 -t greater -p 0.05 -r  -f 0

# parsing clusters...
# 66910 sequences extracted from 5988 clusters

# total experiment sequence ids = 26283
# total control    sequence ids = 66908

# parse_Pfam_freqs: set1 = 623 Pfams set2 = 1560 Pfams

# fisher exact test type: 'greater'
# multi-testing p-value adjustment: fdr
# adjusted p-value threshold: 0.05

# total annotated domains: experiment=1375 control=4086

#PfamID counts(exp)     counts(ctr)     freq(exp)       freq(ctr)       p-value p-value(adj)    description
```
Thanks!

**Comment by eead-csic-compbio** [comment]
Sorry korinalb, I missed somehow your message. Can you compress and share your data so that I can check it locally? 
Thanks, Bruno

**Comment by eead-csic-compbio** [comment]
That means no domains are enriched with FDR cutoff
