### ISSUE TITLE
ERROR: find_COGs

### ISSUE THREAD

**Issue by Sanrrone** [eead-csic-compbio/get_homologues#4]
Dear chic-compbio staff, I don't know why im getting this error, if I modify the coverage the script run is success, but C 100 (with S 100) give the COGs error. the lines are the following:
> perl get_homologues.pl -d cdifficile_all -n 16 -C 100 -S 100 -G
> \# /home/ecastron/programs/get_homologues-x86_64-20160201/get_homologues.pl -i 0 -d cdifficile_all -o 0 -e 0 -f 0 -r 0 -t all -c 0 -z 0 -I 0 -m local -n 16 -M 0 -G 1 -P 0 -C 100 -S 100 -E 1e-05 -F 1.5 -N 0 -B 50 -b 0 -s 0 -D 0 -g 0 -a '0' -x 0 -R 0 -A 0
> 
> \# WARNING : cannot lock files in /lustre/groups/cbi/ecastron/Sandro/mayor/assembled/white_list_no_redecont/cdifficile_all_homologues ,
> \# please ensure that no other instance of the program is running at this location
> 
> \# results_directory=/lustre/groups/cbi/ecastron/Sandro/mayor/assembled/white_list_no_redecont/cdifficile_all_homologues
> \# parameters: MAXEVALUEBLASTSEARCH=0.01 MAXPFAMSEQS=250 BATCHSIZE=100 KEEPSCNDHSPS=1
> 
> \# checking input files...
> \# 97-16_S15.faa 3908
> \# CGB1038-2_S2.faa 3688
> \# CGB1038-3_S3.faa 3685
> \# CGB1038-5_S5.faa 3849
> \# CGB1038-6_S6.faa 3852
> \# difficile630.faa 3823
> \# difficileCIP107932.faa 3688
> \# difficileQCD-32g58.faa 4162
> \# difficileQCD-66c26.faa 3677
> \# difficilecd196.faa 3630
> \# difficiler20291.faa 3702
> 
> \# 11 genomes, 41664 sequences
> 
> \# taxa considered = 11 sequences = 41664 residues = 12654511 MIN_BITSCORE_SIM = 19.2
> 
> \# mask=difficilecd196_f0_alltaxa_algCOG_e0_C100_S100_ (_algCOG_C100_S100)
> 
> \# skipped genome parsing (cdifficile_all_homologues/tmp/selected.genomes)
> 
> \# skip BLAST searches and parsing
> 
> \# WARNING: please remove/rename results directory:
> \# '/lustre/groups/cbi/ecastron/Sandro/mayor/assembled/white_list_no_redecont/cdifficile_all_homologues/'
> \# if you change the sequences in your .gbk/.faa files or want to re-run
> 
> \# creating indexes, this might take some time (lines=3.27e+06) ...
> 
> \# construct_taxa_indexes: number of taxa found = 11
> \# number of file addresses/BLAST queries = 4.2e+04
> 
> \# clustering orthologous sequences
> \# checking lineage-specific expansions
> \# making COGs
> \# ERROR: find_COGs (/home/ecastron/programs/get_homologues-x86_64-20160201//bin/COGsoft/COGtriangles/COGtriangles ) failed to terminate job

can you help me? regards

**Comment by eead-csic-compbio** [comment]
Dear Sandro, most likely you are running two instances of get_homologues.pl simultaneously? Only one can be run at a time on the same output folder. Let me know if this is the case,
Bruno

**Comment by Sanrrone** [comment]
really quick the support, thanks!, I only run one instance of get_homologues.pl at time, but using the same folder output by default, (just modifying the cluster algorithm), with BDHH and OMLC works, but COG triangle crash.

**Comment by eead-csic-compbio** [comment]
Hi Sandro, I was able to reproduce this using the sample data. 
It seems that COGtriangles has trouble when the coverage cutoff is > 0.99.
I will post a new release fixing this in a while, in the meantime you can set -C 99 when calling -G

**Comment by eead-csic-compbio** [comment]
Fixed in release 12072016 (v2.0.18).
