### ISSUE TITLE
Method used to define 'Pangenome size' with -c option?

### ISSUE THREAD

**Issue by jpiechura** [eead-csic-compbio/get_homologues#40]
Hello, 

I am working with a list of 20 closely related bacterial genomes. I analyze them with get_homologues.pl with both orthoMCL and COG triangles, and then run compare_clusters.pl to obtain a pangenome matrix from both result sets, resulting in ~10,000 orthologue clusters. However, if i run compare_clusters.pl with -c with either orthoMCL or COG, the identified pangenome size using all 20 genomes is only ~7,500 genes. I am confused by this discrepancy, as I would expect these two methods to give comparable numbers of orthologue clusters for the 'pangenome'. 

Can you explain how the -c option of compare_clusters.pl calculates pangenome size? Do you know the source of the discrepancy in the above analysis I highlighted?

Best,
Joe

**Comment by brunocontrerasmoreira** [comment]
Hi Joe, there's currently no -c option in compare_clusters.pl, which version of the package are you using? You can check that running perl get_homologues.pl -v,
cheers

**Comment by jpiechura** [comment]
Sorry for the confusion - I am running get_homologues.pl  with -c to calculate pangenome size with sub-samples of the input genomes.

**Comment by brunocontrerasmoreira** [comment]
Hi Joe, please check FAQ "The number of clusters produced with -C 75 -S 70 does not match the pangenome size estimated with option -c" in the manual, URL: http://eead-csic-compbio.github.io/get_homologues/manual/manual.html#SECTION00063000000000000000
