### ISSUE TITLE
compare_clusters.pl argument parsing problem

### ISSUE THREAD

**Issue by bioinformatist** [eead-csic-compbio/get_homologues#41]
Hey, I use both BDBH and OMCL algorithm and got two directories `GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algBDBH_e0_` and `GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algOMCL_e0_`. Then, to pick intersection between them, I use compare_clusters.pl, but I found that only the first directory will be used if there's a blank after comma. 

For instance, if I send `-d` parameter as `evo_homologues/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algBDBH_e0_, evo_homologues/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algOMCL_e0_`, the STDOUT like:

```pre
# ../get_homologues-x86_64-20190102/compare_clusters.pl -d evo_homologues/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algBDBH_e0_, -o evo_intersection -n 0 -m 0 -t 0 -I  -r 0 -s 0 -x 0 -T 0

# number of input cluster directories = 1

# parsing clusters in evo_homologues/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algBDBH_e0_ ...
# cluster_list in place, will parse it (evo_homologues/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algBDBH_e0_.cluster_list)
# number of clusters = 1245

# intersection output directory: evo_intersection
# intersection size = 1245 clusters

# intersection list = evo_intersection/intersection_t0.cluster_list


# WARNING: Venn diagrams are only available for 2 or 3 input cluster directories
```

See, only the first one is taken in for analysis.

And if I send them only separated by comma as `-d evo_homologues/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algBDBH_e0_,evo_homologues/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algOMCL_e0_`, it works well:

```pre
# ../get_homologues-x86_64-20190102/compare_clusters.pl -d evo_homologues/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algBDBH_e0_,evo_homologues/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algOMCL_e0_ -o evo_intersection -n 0 -m 0 -t 11 -I  -r 0 -s 0 -x 0 -T 0

# number of input cluster directories = 2

# parsing clusters in evo_homologues/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algBDBH_e0_ ...
# cluster_list in place, will parse it (evo_homologues/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algBDBH_e0_.cluster_list)
# number of clusters = 1214
# parsing clusters in evo_homologues/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algOMCL_e0_ ...
# cluster_list in place, will parse it (evo_homologues/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algOMCL_e0_.cluster_list)
# number of clusters = 1173

# intersection output directory: evo_intersection
# WARNING: output directory evo_intersection already exists, note that you might be mixing clusters from previous runs

# intersection size = 1127 clusters

# intersection list = evo_intersection/intersection_t11.cluster_list

# input set: evo_intersection/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algBDBH_e0_.venn_t11.txt
# input set: evo_intersection/GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algOMCL_e0_.venn_t11.txt

# Venn diagram = evo_intersection/venn_t11.pdf
# Venn region file: evo_intersection/unique_GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algBDBH_e0_.venn_t11.txt (87)
# Venn region file: evo_intersection/unique_GeobacterpickeringiistrainG13_dmd_f0_alltaxa_algOMCL_e0_.venn_t11.txt (46)
```

As we all know, programmers/users always like add single blank behind comma, and I believe that I'm not the one who is blocked by this problem, so can you allow this syntax? Thank you.

**Comment by brunocontrerasmoreira** [comment]
The simple solution for you is to remove that space/blank :-)

In the long-term I guess we could switch it to http://perldoc.perl.org/Getopt/Long.html#Options-with-multiple-values so that the input folders can be added with several -d args .
However that will require testing to ensure backwards compatibility and updating the documentation as well so I'll do that when I have the chance, thanks for the suggestion
