### ISSUE TITLE
Error in reading input genbank files

### ISSUE THREAD

**Issue by aupadrasta** [eead-csic-compbio/get_homologues#42]
ERROR: could not extract sequences from file APCEc01_gbk/.gbk
When trying to submit the genbank files for analysis Am getting this error
ERROR: could not extract sequences from file APCEc01_gbk/.gbk
I have checked the genbank files and they are complete files with nucleotide sequences. Is there anything I was missing out? 
Could you please help me with this
Thanks
Aditya

**Comment by brunocontrerasmoreira** [comment]
Hi Aditya, can you please post that file so I can have a look at it? Thanks
