### ISSUE TITLE
re-run pipeline for compositional analyses using subset of genomes does not use previous data

### ISSUE THREAD

**Issue by efr3m** [eead-csic-compbio/get_homologues#43]
Dear Bruno,
I run the pipeline once including among the genomes an outgrup. I did that for phylogenomics reasons.
Now I would like to perform a compositional analysis based only on the genomes of interest, meaning excluding the outgroup.
I am re-running get_homologues with the `-I` flag (the text includes the names od the file (AB.gbk) I want to include, one per line). However, get_homologues starts a new computation (e.g. making diamond DB and running diamomd).
Is there a possibility of using the previous results for such a task?
Thanks a lot for your time and help!
Best
Stefano

**Comment by brunocontrerasmoreira** [comment]
Hi Stefano, unfortunately that cannot be done, as it only made sense to run DIAMOND against large sequence sets to take advantage of the speed gain. Therefore, each proteome is scanned twice: i) against itself and ii) against all others, and thus when using the -I flag the "others" set changes and needs to be recomputed, BRuno
