### ISSUE TITLE
Question: restarting get_homologues-est

### ISSUE THREAD

**Issue by hydrahamster** [eead-csic-compbio/get_homologues#44]
Hi there,
get_homologues-est ran out of memory. Is there a way to re-start the run continuing from the output so far or is it better to start from scratch?

Thanks,
Liza

**Comment by brunocontrerasmoreira** [comment]
Hi Liza, do you know at what stage it died? If BLAST jobs were completed you can safely remove the tmp/ directory inside the results folder and rerun. If you are not sure about BLAST jobs you can check the size of .blast.gz files and check those that look anormally small, but please double check to make sure you don't keep any incomplete file as that will affect all downstream analyses. 

In addition, are you going to rerun in a larger RAM machine? You can also try option -s to reduce the memory footprint at the cost of speed, 
hope this helps,
Bruno

**Comment by hydrahamster** [comment]
Thank you @brunocontrerasmoreira ^__^ Apologies for the slow response, but that is exactly what I was looking for.
Cheers, 
Liza

**Comment by hydrahamster** [comment]
Just one follow up question - do I simply restart with the exact same set of flags or should I specify the directory with the BLAST output files?

Cheers,
Liza

**Comment by eead-csic-compbio** [comment]
You should use the same flags that affect BLAST, mainly -d and -E.
