### ISSUE TITLE
pfam_enrich.pl can't match ids of 'experiment'

### ISSUE THREAD

**Issue by Zhuxitong** [eead-csic-compbio/get_homologues#45]
I first run command like this:
```
parse_pangenome_matrix.pl -m matrix_t2/pangenome_matrix_t0.tab -B ref.list -a
```
I got file #matrix_t2/pangenome_matrix_t0__pangenes_list.txt#

Then when I run pfam_enrich.pl: 
```
pfam_enrich.pl -d sequence_est_homologues/ -c sequence_est_homologues/A-grandislongest_0taxa_algOMCL_e0_S75_ -x matrix_t2/pangenome_matrix_t0__pangenes_list.txt
```

I got this error:
cannot match ids of 'experiment' sequences.

I checked many times but could hardly find any thing I missed. Can you help ?

**Comment by Zhuxitong** [comment]
I solved the above by add -e parameter to pfam_enrich.pl. My sequences are not ESTs, so it's very strange.

**Comment by eead-csic-compbio** [comment]
Hi, can you please list the commands you issues to generate the clusters? What kind of input did you use, gbk or FASTA files?

**Comment by Zhuxitong** [comment]
Thanks for you kindly reply. I will list my command below:

My input are 11 cds fna files together with their faa files.
fna:
>Cg1g000010.1 gene=Cg1g000010
ATGAACCGCCCCCCGGGGGCCGAAACCGGCAAAAGGCCAAACGGCCCCGATCTTACCCATTTTTCGGCGATCAAACCGCC
GCACGGCTACCCCCCCATCCCGATGCCCCGGACCGCTGGTCCCGTGGGACCAAACGGAAACGGAATCGGAGGCCCGGATC
twin faa:
>Cg1g000010.1 Cg1g000010
MNRPPGAETGKRPNGPDLTHFSAIKPPHGYPPIPMPRTAGPVGPNGNGIGGPDHELRPKPAKPTKRPPILPIFRRSNCRA

First, I used this command to run blastn and  pfam annotation:
get_homologues-est.pl -d sequence/ -S75 -D -n 24 -o

Then generated control clusters:
get_homologues-est.pl -d sequence -M -t 0 -S 75

To got non-cloud clusters and their matrix, I used these:
get_homologues-est.pl -d sequence -M -t 2 -S 75 -n 20
compare_clusters.pl -d sequence_est_homologues/A-grandislongest_2taxa_algOMCL_e0_S75_ -o matrix_t2 -m

Next I wanted to check some absent genes in one taxa, so I used:
parse_pangenome_matrix.pl -m matrix_t2/pangenome_matrix_t0.tab -B ref.list -a
where ref.list looks:
$ cat ref.list
A-grandis_longest.fna.nucl

Finally pfam enrichment were carried out:
pfam_enrich.pl -d sequence_est_homologues/ -c sequence_est_homologues/A-grandislongest_0taxa_algOMCL_e0_S75_ -x matrix_t2/pangenome_matrix_t0__pangenes_list.txt -e

Here I got the problem. If I remove -e, an error, cannot match experiment ids will appear. But my sequences are not ESTs. Later although I can run it successfully, another problems occured: too few pfam domain were enriched and at the end of output fiile, a sort error there:
#PfamID counts(exp)     counts(ctr)     freq(exp)       freq(ctr)       p-value p-value(adj)    description
PF00078 47      270     3.190e-03       1.238e-03       6.176e-08       1.032e-04       Reverse transcriptase (RNA-dependent DNA polymerase)
PF13966 36      191     2.443e-03       8.759e-04       3.877e-07       4.860e-04       zinc-binding in reverse transcriptase
PF00931 171     1674    1.161e-02       7.676e-03       7.256e-07       7.276e-04       NB-ARC domain
PF14223 64      493     4.343e-03       2.261e-03       3.999e-06       3.342e-03       gag-polypeptide of LTR copia-type
PF01582 39      264     2.647e-03       1.211e-03       2.338e-05       1.675e-02       TIR domain
sort: write failed: standard output: Broken pipe
sort: write error

Really strange.

**Comment by Zhuxitong** [comment]
Adding -p 1 to pfam_enrich.pl can solve the 'sort' problem. I guess this has something to do with my system.

**Comment by eead-csic-compbio** [comment]
I will try to replicate this with a different sets of FNA files, unless you want to share yours

**Comment by brunocontrerasmoreira** [comment]
Hi, you do have to use -e as clusters and pfam annotations were computed with get_homologues-est.pl

**Comment by brunocontrerasmoreira** [comment]
I have now updated pfam_enrich.pl and the sort error should be fixed, can you git pull it?

**Comment by Zhuxitong** [comment]
> 
> 
> Hi, you do have to use -e as clusters and pfam annotations were computed with get_homologues-est.pl



> 
> 
> I will try to replicate this with a different sets of FNA files, unless you want to share yours

Sorry my data hasn't been published. There is no big differnece between my data and general FASTA file. Only in the header line, my data looks like: 
```
>name gene=something
```
I don't know if this 'gene=something' matters of not.

**Comment by Zhuxitong** [comment]
> 
> 
> Hi, you do have to use -e as clusters and pfam annotations were computed with get_homologues-est.pl

Yes,  have to use -e, otherwise it will give me the error of 'cannot match experiment of ids'.

**Comment by Zhuxitong** [comment]
> 
> 
> I have now updated pfam_enrich.pl and the sort error should be fixed, can you git pull it?

Thanks! I will pull it.

**Comment by eead-csic-compbio** [comment]
I am closing this now
