### ISSUE TITLE
Feature request - add input file name to cluster fasta header

### ISSUE THREAD

**Issue by osuchanglab** [eead-csic-compbio/get_homologues#46]
When parsing the fasta format output of parse_pangenome_matrix.pl, I often run into issues determining which sequences came from which genomes, or reformatting headers to only list the strain name (ie for making a partitioned alignment, etc.). This is especially the case when RefSeq annotated genomes are included, as strains now have non-redundant protein ids that are no longer unique. 

It would be nice to have an option to include the input filename (strainA.gbk) included in the header line of each sequence so that it is easy to separate them out and not have to deal with inconsistent or non-unique labeling of strain names.

**Comment by brunocontrerasmoreira** [comment]
Hi, can you please:
i) share 3 RefSeq genome accessions so that I can reproduce your error
ii) explain a little bit better what output you refer to, as parse_pangenome_matrix.pl mainly produces flat files with lists of genes
Thanks, Bruno

**Comment by osuchanglab** [comment]
Hi, thank you for looking into this. I apologize, I meant the fasta output from compare_clusters.pl, ie from running:
compare_clusters.pl -d ./genomes_homologues/refstrain_f0_0taxa_algOMCL_e0_ -o ./genomes_homologues/genomes_ncbi_nucl_OMCL -m -T -n

Here are several accessions with non-unique ID's:
GCF_001590795.1
GCF_900094575.1
GCF_000261785.1

I've also attached an example cluster file [1690_hypothetical_protein.trimmed.fna.zip](https://github.com/eead-csic-compbio/get_homologues/files/3302981/1690_hypothetical_protein.trimmed.fna.zip) trimmed to show a few non-unique ID sequences. As you can see, the protein ID:WP_036013800.1 is not unique, and the section containing the strain name is incomplete ("|[Bradyrhizobium yuanmingense]|") with the strain name in the next column, or not, or duplicated, depending on the strain. It would be really convenient to have an extra column with the input file name so that regardless of how genbank files are annotated I can still separate out what came from where. Thank you!

**Comment by brunocontrerasmoreira** [comment]
Hi again, I have updated the code to include the original filename in the FASTA header. Let me know if you can git pull and test it and I'll create a new release.
By the way, I also updated download_genomes_ncbi.pl so that it works with such assembly ids,
Bruno

**Comment by brunocontrerasmoreira** [comment]
Forgot to say, you should not need to run from scratch. Removing the fasta, faa, fna files in the _homologues folder is enough, then simply re-run the same command

**Comment by osuchanglab** [comment]
Hi, Thank you for the update, I've run the github version and it produces correct output with the input filename included in each fasta header. Thank you for adding this feature, it will save me a ton of time in my analyses!
