### ISSUE TITLE
plot core-genome and pan-genome plots

### ISSUE THREAD

**Issue by ga23981** [eead-csic-compbio/get_homologues#48]
Could you please help me with this one:

I need to plot core-genome and pan-genome plots as shown in Fig. 16 of the manual.
In order to get these plots I am executing the following script first that will give me a .tab file
get_homologues.pl -d faa -c -M -n 25 as suggested in 4.8.4
faa directory contains all the amino acid sequences of my bacterial strains.
The above script will generate faa_homologue folder where I should find the .tab file to used further.

I have two questions here:

The above script has been running for last four days and hasn't ended. Does it take this much time? I have assigned 40 Gb of memory, 200 CPU hrs and 25 threads on a single node for 81 bacterial genomes. There are a total of 14,452 genes, including 3153 core genes, 3799 soft core, 3845 shell and 6806 cloud genes.

Do I have to use the .tab file produced by the above script only as input in the following way:
plot_pancore_matrix.pl -i xyz.tab -f core_Tettelin
xyz.tab file is the file that is expected to be generated by get_homologues.pl as shown above (first).
or
Can I use any other already generated pangenome.tab files by earlier used scripts?

Thank you
Gaurav

**Comment by eead-csic-compbio** [comment]
Hi Gaurav, 
if you are analyzing 81 genomes bacterial genomes you would need to compute in parallel. If your system is multi-core your BLASTP searches will be forked 25x with -n 25. However, the integration of results afterwards, in particular those required for -c, will be done serially. In those cases running -m cluster really makes a difference, but you'll need to set up your local gridengine cluster in that machine, as explained in [the manual](http://eead-csic-compbio.github.io/get_homologues/manual/manual.html#SECTION00033000000000000000) . I will look to support LSF soon, but that's not ready yet.

If you want to plot pangenome growth (both core & pan) you do need that file, there's no way to produce a Tettelin plot with the other .tab files,
Bruno

**Comment by ga23981** [comment]
Thank you, Bruno.
