### ISSUE TITLE
Not able to get proper Tettelin fit to OrthoMCL clusters to estimate the size of the

### ISSUE THREAD

**Issue by ga23981** [eead-csic-compbio/get_homologues#49]
plot_pancore_matrix.pl -i pan_genome_algOMCL.tab -f core_Tettelin
Also tried, plot_pancore_matrix.pl -i pan_genome_algOMCL.tab -f core_both

# core_Tettelin fit failed to converge
# core_Willenbrock fit failed to converge

**Comment by eead-csic-compbio** [comment]
Hi, I believe the reason is you need to use the core_genome_algOMCL.tab to fit the core. The one you are using will fit -f pan, 
Bruno

**Comment by ga23981** [comment]
Oops, sorry about that. My bad!

Many thanks,

Gaurav

**Comment by ga23981** [comment]
Sorry about that mistake at my end. 
I worked perfectly fine with -f pan option.

Thank you!
