### ISSUE TITLE
Cloud_genes

### ISSUE THREAD

**Issue by ga23981** [eead-csic-compbio/get_homologues#50]
I used 81 strains for pan-genome studies and all 81 strains are contributing to cloud genes ranging from 1 gene to 498 genes. Cloud genes come from ~2% of the population (rare genes) is what I know. How do I understand this contribution of cloud genes from all the 81 strains of bacteria?
[Book1.xlsx](https://github.com/eead-csic-compbio/get_homologues/files/3704865/Book1.xlsx).

Also, can we identify unique genes?

**Comment by brunocontrerasmoreira** [comment]
Hi, the compartments/classes are defined in table 5 of the [manual](http://eead-csic-compbio.github.io/get_homologues/manual/manual.html#SECTION00058000000000000000). There cloud genes are defined as strain-specific following https://doi.org/10.1016/j.mib.2014.11.016 . In the code the cutoff is defined as the class next to the most populated non-core cluster class, which is usually that of unique genes (occupancy=1). Therefore, in most cases cloud genes have occupancy [1,2].
Cloud genes are novel genes found in each genome, but are also typically bad gene models, assembly artifacts and so on. So you usually want to validate them if they are important for your study.
