### ISSUE TITLE
typo-like in get_homologues-est manual

### ISSUE THREAD

**Issue by Rodolfo47** [eead-csic-compbio/get_homologues#51]
Hello Pablo and Bruno,

I'm starting in the use of your great program get_homologues and I've found a tiny typo

In this [manual](http://eead-csic-compbio.github.io/get_homologues/manual-est/manual-est.html#SECTION00052000000000000000),

in section 4.2 the code used to make the plot are:
`./plot_matrix_heatmap.sh -i sample_[...]/Esterel_alltaxa_algOMCL_e0_Avg_identity.tab \
  -t "clusters=66" -k "Average Nucleotide Identity" -o pdf -m 28 -v 35 -H 9 -W 10`

wile I think it must read:

`./plot_matrix_heatmap.sh -i [...]/[...]_alltaxa_algOMCL_e0_Avg_identity.tab \
  -t "clusters=66" -k "Average Nucleotide Identity" -o pdf -m 28 -v 35 -H 9 -W 10`

thats all, sorry if this is very vain but it caused a small error and I think it can be solved

your git and docker file are really cool
Cheers

**Comment by eead-csic-compbio** [comment]
Thanks @Rodolfo47 for your suggestion. In this case I prefer to leave it as is to help users know which file is being used in that command. However, if you find other bugs or have suggestions they are welcome, Bruno
