### ISSUE TITLE
Displaying locus tags in output

### ISSUE THREAD

**Issue by tslaird** [eead-csic-compbio/get_homologues#52]
When running get_homologues on multiple .gbk/.gbff files is it possible to incorporate the "locus_tag" feature in the results? Is it also possible to not truncate the names of proteins?

**Comment by brunocontrerasmoreira** [comment]
Hi, you can play around with gene/protein ids by commenting out lines in sub extract_CDSs_from_genbank in lib/PhyTools.pm

For instance, commenting out lines 1042-1045 in https://github.com/eead-csic-compbio/get_homologues/blob/master/lib/phyTools.pm#L1042 by adding a # at the beginning of the line will skip taking the protein_id as identifier and then locus_tag would be taken instead.

Similarly, commenting out line 1064 at
https://github.com/eead-csic-compbio/get_homologues/blob/master/lib/phyTools.pm#L1064
will not shorten gene names,
hope this helps,
Bruno
