### ISSUE TITLE
problem with ./parse_pangenome_matrix.pl

### ISSUE THREAD

**Issue by sohini5981** [eead-csic-compbio/get_homologues#53]
Hello,

I have been using your incredible program for some time. It's great. The manuals are lucid enough to guide me whenever I have to face any troubles. However, recently I have been facing a problem that is not getting solved. I am a self-taught person when it comes to bioinformatics and programming.

I am working with 2 sets of rhizobia (WBAH; WBOS),6 strains per set. I have been running the GET_HOMOLOGUES on these genomes to find out the core-shell-cloud genes. The combinations being-

1.WBAH (to find the genes shared/specific among them)

2.WBOS (to find the genes shared/specific among them)

3. WBAH+WBOS (to find the genes shared/specific among WBAH and WBOS)

While 1. and 3. worked fine, I am unable to use the  ./parse_pangenome_matrix.pl   for no.2.

I am getting an error "Error in rep("orange", each = 5 - 5 - 1) : invalid 'each' argument"

I did not get this error when I ran the same code on 1. and 3  at the same time.

I am attaching the logs for the successful run and the unsuccessful runs  
[failed run.txt](https://github.com/eead-csic-compbio/get_homologues/files/3964729/failed.run.txt)
[successful run log.txt](https://github.com/eead-csic-compbio/get_homologues/files/3964730/successful.run.log.txt)

I checked the files produced during the unsuccessful run. The shell genes represented by orange color were not produced and I did not find any image files. It is strange since the ./parse_pangenome_matrix.pl works fine with my other genomes at the same time

It will be helpful if you could shed some light on what is going wrong.
Let me know if you need any info from my side. I ran the following command to generate the clusters in the three cases.
./get_homologues.pl -d OS -t 0 -G -M
./get_homologues.pl -d AH -t 0 -G -M
./get_homologues.pl -d AHOS -t 0 -G -M

**Comment by eead-csic-compbio** [comment]
Hello, thanks for the detailed information. I believe this might be due to the soft-core class having 0 clusters. Can you please share your pangenome matrix so that I can reproduce this and fix it? Bruno

**Comment by sohini5981** [comment]
[pangenome_matrix_t0.txt](https://github.com/eead-csic-compbio/get_homologues/files/3968578/pangenome_matrix_t0.txt)

Hello,
Thank you for replying. Please find the attached  pangenomematrix.

The log that is being generated (see the previous email attachment under 'failed run ') is also different.(Error in rep("orange", each = 5 - 5 - 1) : invalid 'each' argument
Execution halted)
It is not possible that there will be zero clusters under the shell category as these strains have several overlapping genes in some but not all.(shell genes)

Regards 

Sohini

**Comment by brunocontrerasmoreira** [comment]
Thanks Sohini, I confirm the issue is due to the small number of genomes in the pangenome matrix (n=6). I have npw change the code to make sure the occupancy cutoff for cloud clusters is always smaller than than of soft-core clusters. Just changed one line of code:

https://github.com/eead-csic-compbio/get_homologues/blob/c48fc2be6fbac6ce2879ac6f5e25ff89ef7d9873/parse_pangenome_matrix.pl#L665

If you git pull you should now be able to produce your plots,
Bruno

**Comment by sohini5981** [comment]
Hello,

Thank you. It works fine now.
