### ISSUE TITLE
Error while running compare_clusters.pl script

### ISSUE THREAD

**Issue by dineshkumarsrk** [eead-csic-compbio/get_homologues#54]
I tried to run the test data which is given in the `get_homologues tool.` As per the manual instruction I have successfully performed the first three steps by using the `perl` `script get_homologues.`  Further, I tried to run `compare_clusters.pl` script  but end up with an error. I tried in all the possible way to run it but failed. Please note that, previous three steps has generated all the necessary folders and files, but while running `compare_clusters.pl` those folders are not recognised by the script and shows error like,  `No such file or directory.` Therefore, kindly help me to fix this issue. I look forward to hearing from you.
`ga@pls:~/Documents/tools/get_homologues-master$ ./compare_clusters.pl -o sample_intersection -d \ sample_buch_fasta_homologues/BuchaphCc_f0_alltaxa_algBDBH_e0_, \ sample_buch_fasta_homologues/BuchaphCc_f0_alltaxa_algCOG_e0_,  \ sample_buch_fasta_homologues/BuchaphCc_f0_alltaxa_algOMCL_e0_

# ./compare_clusters.pl : cannot find directory  sample_buch_fasta_homologues/BuchaphCc_f0_alltaxa_algBDBH_e0_ , please check
`

`ga@pls:~/Documents/tools/get_homologues-master$ ./compare_clusters.pl -o sample_intersection -d sample_buch_fasta_homologues/BuchaphCc_f0_alltaxa_algBDBH_e0_, sample_buch_fasta_homologues/BuchaphCc_f0_alltaxa_algCOG_e0_, sample_buch_fasta_homologues/BuchaphCc_f0_alltaxa_algOMCL_e0_

# ./compare_clusters.pl -d sample_buch_fasta_homologues/BuchaphCc_f0_alltaxa_algBDBH_e0_, -o sample_intersection -n 0 -m 0 -t 0 -I  -r 0 -s 0 -x 0 -T 0

# number of input cluster directories = 1

# parsing clusters in sample_buch_fasta_homologues/BuchaphCc_f0_alltaxa_algBDBH_e0_ ...
# cluster_list in place, will parse it (sample_buch_fasta_homologues/BuchaphCc_f0_alltaxa_algBDBH_e0_.cluster_list)
# number of clusters = 239

# intersection output directory: sample_intersection
# WARNING: output directory sample_intersection already exists, note that you might be mixing clusters from previous runs

# intersection size = 239 clusters

# intersection list = sample_intersection/intersection_t0.cluster_list

# WARNING: Venn diagrams are only available for 2 or 3 input cluster directories
`

**Comment by brunocontrerasmoreira** [comment]
Dear Dinesh, the paths after -d must have no spaces after the commas, Bruno

**Comment by dineshkumarsrk** [comment]
Thank you for your valuable information. Now it works. once again, thank
you.
