### ISSUE TITLE
Forcing GET_HOMOLOGUES-EST to include one gene per sample

### ISSUE THREAD

**Issue by soungalo** [eead-csic-compbio/get_homologues#55]
Hello,
I was wondering if there is an option to force the software to produce clusters that have at most one gene per sample (i.e. each sample has 0 or 1 genes). In other words, I am looking for an option to avoid paralogs and orthologs mixed within the same cluster.
Thanks!

**Comment by brunocontrerasmoreira** [comment]
Hi, you should add -e to your get_homologues command to exclude inparalogues. This way you get single-copy clusters. Alternatively you can filter those clusters with compare_clusters.pl using options -t or -I
Hope this helps, Bruno

**Comment by soungalo** [comment]
Thanks for the quick reply. Sorry I wasn't clear enough, but what I meant was not to simply discard clusters with paralogs or paralogs out of clusters. I was hoping for a way to break clusters with paralogs into smaller clusters in a way that will ensure no paralogs reside within the same cluster. Is there an existing tool to do that?

**Comment by brunocontrerasmoreira** [comment]
Hello again.
While script check_BDBHs.pl can help you inspect the similarity relationships among sequences in a particular cluster, I am afraid there's no ready to go way to break down clusters as you describe. In addition, note it might be tricky to tell which gene is the paralogue and which is the orthologue in many cases, even if you compute trees, Bruno

**Comment by soungalo** [comment]
Thank you for your advice.
