### ISSUE TITLE
Interrogating a pangenome matrix

### ISSUE THREAD

**Issue by kuzman1306** [eead-csic-compbio/get_homologues#56]
Dear get_homologues team,

I would like to use the script parse_pangenome_matrix.pl to produce a map of genes present in the genome A, but absent in the genome B. I used the following command:
```
parse_pangenome_matrix.pl -m sample_intersection/pangenome_matrix_t0.tab \
-A path_to_the_directory/A.txt -B path_to_the_directory/B.txt -g \
-p '(name of the taxon listed in A.txt, as determined by the option -l)'
```
As an input, I used gbk files produced by prokka from two bacterial genomes containing multiple replicons/chromosomes. I used OMCL algorithm for obtaining a pangenome matrix  and script compare_clusters.pl to compile the corresponding pangenome matrix.

However, I am getting the following error:

```
# plotting pangenes in genomic context...
# /get_homologues/parse_pangenome_matrix.pl: error, cannot find genome coordinates in pangenomic clusters, cannot make plot
```
I wonder if you could help me with this issue.

I look forward to hearing from you.

Sincerely,

Nemanja

**Comment by brunocontrerasmoreira** [comment]
Hello, can you post one of those pangene clusters in FASTA format? Can you see coords in the headers? Bruno

**Comment by kuzman1306** [comment]
Hi,
Thank you for your quick answer. I attached the fasta file.
Cheers,
Nemanja


[9_yceJ_1.txt](https://github.com/eead-csic-compbio/get_homologues/files/4251327/9_yceJ_1.txt)

**Comment by eead-csic-compbio** [comment]
Hi Nemanja, thanks for raising this as I found a bug that I believe might have been around for some releases. I have now added parse_pangenome_matrix.pl -p to the test suite to prevent similar bugs in the future. This should now be fixed, you can either git pull or take the latest release 

https://github.com/eead-csic-compbio/get_homologues/releases/tag/v3.3.2

Let me know how it goes with your data,
Bruno

**Comment by kuzman1306** [comment]
Dear Bruno,

Thank you for your effort. Since I am using docker image, is this change included there?

Cheers,

Nemanja

**Comment by brunocontrerasmoreira** [comment]
In that case you'll have to wait until I update the docker container tomorrow. In the meantime you might wanto to do ```git pull``` inside the get_homologues folder inside docker and try it out, Bruno

**Comment by brunocontrerasmoreira** [comment]
Please check it out at https://hub.docker.com/r/csicunam/get_homologues/tags

**Comment by kuzman1306** [comment]
Dear Bruno,
Thank you very much for your notification. I do not have an access to the PC in the moment, but will let you know how the updated version works with my data tomorrow.
Cheers,
Nemanja

**Comment by kuzman1306** [comment]
Dear Bruno,
Sorry for the delayed answer. It works perfectly now!
Thank you for your effort.
Cheers,
Nemanja
