### ISSUE TITLE
core gene sequences

### ISSUE THREAD

**Issue by ga23981** [eead-csic-compbio/get_homologues#57]
Hello,

Could you please help me with this:

I want to align the core sequences from each bacterial strain that I used in my study and plot a phylogenetic tree based on alignment of sequences. How can I get the core sequences representative of each bacterial strain?

**Comment by eead-csic-compbio** [comment]
Hi, it sounds like you need to run get_homologues followed by get_phylomarkers. Please check the tutorial and documentation at https://github.com/vinuesa/get_phylomarkers . The easiest way if probably to run the docker image so that dependencies are taken care of, Bruno

**Comment by ga23981** [comment]
Hi Bruno,

I tried executing the get_phylomarkers like this:

singularity exec
/usr/local/singularity-images/get_phylomarkers-2.2.8.1.simg
run_get_phylomarkers_pipeline.sh -R 2 -t DNA

I have the same no. of .fna and .faa files

Got the following error:

 [0;31m >>> ERROR: Input FASTA files do not contain the same number of
sequences...

Could you please suggest me if I need to concatenate all my sequences in
each file into one or is there is something else?

Thank you
GAurav

**Comment by eead-csic-compbio** [comment]
Good morning Gaurav,
the clusters passed to get_phylomarkers indeed need to have 1 copy per taxon.

One way to ensure this is to use compare_clusters.pl as discussed in the tutorial and in issue  https://github.com/vinuesa/get_phylomarkers/issues/3

Another way would be to use get_homologues -e as discussed on issue https://github.com/vinuesa/get_phylomarkers/issues/2

Hope this helps,
Bruno

**Comment by ga23981** [comment]
Many thanks, Bruno, I will look into it. Your help is much appreciated.

Gaurav

**Comment by ga23981** [comment]
Hi Bruno,

Thank you for the directions. It worked for me. I was able to successfully
execute the program using the below command.

singularity exec
/usr/local/singularity-images/get_phylomarkers-2.2.8.1.simg
run_get_phylomarkers_pipeline.sh -R 2 -t DNA

It generated several files and directories. I am specifically looking for a
phylogenetic tree that would be constructed out of the core gene sequences.
Could you please suggest me where can I find it? or do I need to plot it
using the Newick file generated?

Your help is much appreciated.

Thank you
Gaurav

**Comment by vinuesa** [comment]
Hi Gaurav, thanks for you interest in get_homologues and get_phylomarkers.

You are close to it: please cd into the get_phylomarkers_run_* directory generated where you launched the get_phylomarkers run. Then cd into PhiPack/non_recomb_cdn_alns/top_*_markers_ge*perc subdirectory, where you will find the concat_nonRecomb_KdeFilt_iqtree_*_ed.sptree file, which is the core-genome ML phylogeny estimated under the *model from the concatenated alignments of top-ranking markers. 

In summary, the relative path to the concat_nonRecomb_KdeFilt_iqtree_*_ed.sptree file looks like this, starting from the directory where you launched the run:

./get_phylomarkers_run_AIR1tDNA_k1.5_m0.7_Tmedium_30Mar20/PhiPack/non_recomb_cdn_alns/top_16_markers_ge70perc

Please have a look at the paper https://pubmed.ncbi.nlm.nih.gov/29765358/ , manual https://vinuesa.github.io/get_phylomarkers/#get_phylomarkers-manual and tutorial pages for the details. 

Hope this helps.
Take care!

**Comment by ga23981** [comment]
Many thanks, Bruno for all your help and support throughout this process.

I did cd
core_faa_fna/get_phylomarkers_run_AIR2tDNA_k1.5_m0.7_Tmedium_30Mar20/PhiPack/non_recomb_cdn_alns

and find the following files and directories but could not find top_
*_markers_ge*perc subdirectory

alltrees.nwk
dotplot_and_bxplot_kdeDensity_dist_dissim_topo_TRUE.svg
 IQT_best_model_counts_for_gene_trees.tsv
 IQT_DNA_gene_tree_Tmedium_stats.tsv
 IQT_gene_trees_from_non_recombinant_kdeOK_codon_alignments.tgz
IQT_MJRC_tree.nwk
iqtree_output_files.tgz
kde_dfr_file_all_gene_trees.tre.tab
kde_ok
kde_outlier_files_all_gene_trees.tre.out
kde_outliers
kde_stats_all_gene_trees.tre.out
non_recombinant_kdeOK_codon_alignments.tgz
no_tree_branches.list
parallel_bxplots_kdeDensity_dist_dissim_topo_TRUE-FALSE.svg
popGen
sorted_IQT_lnL_mset_gene_trees.tsv

Am I missing something?

Gaurav

**Comment by vinuesa** [comment]
Hi again Gaurav,

I didn't notice that you ran "run_get_phylomarkers_pipeline.sh -R 2 -t DNA", that is with -R 2
As indicated on the command-line help and in the online manual/tutorials, if you want to perform a phylogenetic analysis you should invoke the pipeline with -R 1

 REQUIRED:
    -R <integer> RUNMODE
       1 select optimal markers for phylogenetics/phylogenomics (genomes from different species)
       2 select optimal markers for population genetics (genomes from the same species)
    -t <string> type of input sequences: DNA|PROT

-R 2 is to estimate basic population genetic parameters!

So please run again with the following line: 
"run_get_phylomarkers_pipeline.sh -R 1 -t DNA"

Hope this helps,
best,
Pablo

**Comment by ga23981** [comment]
Many thanks, Pablo. Appreciate your help.

Regards
Gaurav

**Comment by ga23981** [comment]
Hello Pablo,

Uing the command below
singularity exec
/usr/local/singularity-images/get_phylomarkers-2.2.8.1.simg
run_get_phylomarkers_pipeline.sh -R 1 -t DNA

I get the following error message
ERROR! The expected output file
sorted_aggregated_support_values4loci_ge70perc.tab was not produced, will
exit now!

Please suggest.

Thank you
Gaurav

**Comment by vinuesa** [comment]
Dear Gaurav,

thanks for your feedback and patience. I've updated the get_phylomarkers distro on GitHub and built a new Docker image. Both run fine on my ubuntu 18.04 box. Could you please make a new docker pull, by issuing the following command from your terminal:

docker pull csicunam/get_homologues:latest

Please let me know if you still encounter problems.
Take care,
Pablo
