### ISSUE TITLE
plot_matrix_heatmap.sh error

### ISSUE THREAD

**Issue by kuzman1306** [eead-csic-compbio/get_homologues#58]
Dear get_homologues Team,

I was trying to produce pangenome plot, but getting the following error:

```
plot_matrix_heatmap.sh -i pangenome_matrix_t0.tab -o svg   -r -H 8 -W 14 -m 28 -t "sample pangenome (clusters=45538)" -k "genes per cluster"

##############################################################################################
>>> plot_matrix_heatmap.sh vv1.0.4_31Jan18 run started at 2020_04_20-00.31.11
        working directory : /home/you/get_homPhy/sample_intersection
        input tab_file : pangenome_matrix_t0.tab | sim_cutoff : 100 | max_decimals : 0
        subset_matrix : 0 | regex :
        text:sample pangenome (clusters=45538)|margin_hor:28|margin_vert:18|points:15
        angle:45|charExp:1.0|right_margin:10
        width:14|height:8|outformat:svg
        reorder_clusters:1|remove_colnames:1|key_xaxis:genes per cluster|do_bioNJ:0
        k:

##############################################################################################

mv: cannot move 'ed' to 'pangenome_matrix_t0.tab': Operation not permitted
# Plotting file pangenome_matrix_t0_heatmap.svg
Error in library("gplots") : there is no package called ‘gplots’
Calls: suppressPackageStartupMessages -> withCallingHandlers -> library
Execution halted
>>> ERROR: file pangenome_matrix_t0_heatmap.svg was NOT produced.

>>> You can try option -C or alternatively remove columns in the matrix.

>>> ERROR: file ANDg_meand_silhouette_width_statistic_plot.svg was NOT produced!

>>> ERROR: file  was NOT produced!

rm: cannot remove 'Rplots.pdf': No such file or directory

```

I tried docker images "latest" and "10032020-10Jan20" on Ubuntu  16.04 LTS and Ubuntu 18.04 LTS but got the same error.

I wonder if you could help me with this issue.

I look forward to hearing from you.

Sincerely,

Nemanja

**Comment by brunocontrerasmoreira** [comment]
Thanks Nemanja for reporting this. Me and @pvinuesa  are indeed experiencing trouble recently when building the docker images, particularly with the R dependencies, which seem to be affecting you. I will add a test for this script and rebuild the image. We'll see if that works, Bruno

**Comment by brunocontrerasmoreira** [comment]
Hi @kuzman1306 , indeed the docker container did not contained all of the R dependencies for that script. In addition we will update that script in an attempt to make it simpler and come back to you,
Bruno

**Comment by marsilva248** [comment]
I am also having the same issue and was hoping you could help me.
When trying to produce a heatmap from the pangenome matrix, as shown in
Fig.12 in the manual, I get the error (I tried also using a udocker container and got the same error message):

##############################################################################################
>>> plot_matrix_heatmap.sh vv1.0.4_31Jan18 run started at 2020_06_22-21.27.41
        working directory : /data/yeastgenomics/msilva/Torulaspora/results/get_homologues
        input tab_file : Torulaspora_intersection2/pangenome_matrix_t0.tab | sim_cutoff : 100 | max_decimals : 0
        subset_matrix : 0 | regex :
        text:Torulaspora_intersection2/pangenome_matrix_t0.tab|margin_hor:18|margin_vert:18|points:15
        angle:45|charExp:1.0|right_margin:10
        width:15|height:10|outformat:pdf
        reorder_clusters:1|remove_colnames:0|key_xaxis:Value|do_bioNJ:0
        k:

##############################################################################################

# Plotting file Torulaspora_intersection2/pangenome_matrix_t0_heatmap.pdf
Error in library("gplots") : there is no package called ‘gplots’
Calls: suppressPackageStartupMessages -> withCallingHandlers -> library
Execution halted
>>> ERROR: file Torulaspora_intersection2/pangenome_matrix_t0_heatmap.pdf was NOT produced.

>>> You can try option -C or alternatively remove columns in the matrix.

>>> ERROR: file ANDg_meand_silhouette_width_statistic_plot.pdf was NOT produced!

>>> ERROR: file  was NOT produced!

rm: cannot remove 'Rplots.pdf': No such file or directory


Thanks in advance,
Margarida Silva

**Comment by brunocontrerasmoreira** [comment]
Dear @kuzman1306 @marsilva248 , we have created a new version of the docker container (02062020-02Apr20, check it at https://hub.docker.com/r/csicunam/get_homologues/tags) that ships with binary R packages to make sure they work and there are less compilation problems. That's why the image size is now larger.
In addition, the build process now explicitely tests the R depencies of this script ( make testR).
Can you please test the new image and tell how it goes?

Note: @pvinuesa is working on a new version of plot_matrix_heatmap.sh

**Comment by marsilva248** [comment]
@brunocontrerasmoreira thank you for your help and sorry for the late response.
I was able to fix the previous problem but couldn't produce the heatmap. I tried also with the example files provided (''sample_plasmids_gbk''), to make sure the problem wasn't with my data, but also got this error:

> Warning message:
> In as.dist.default(100 - dfr.num.mat) : non-square matrix
> Error in rect(xleft, ybottom, xright, ytop, border = border[n], density = density,  :
> cannot mix zero-length and non-zero-length coordinates
> Calls: %>% ... withVisible -> <Anonymous> -> rect.dendrogram -> rect
> Execution halted

Thanks in advance,
Margarida Silva

**Comment by brunocontrerasmoreira** [comment]
Obrigado Margarida,
we are aware of that error message, in fact @pvinuesa is working on a new improved version.
However, that part of the code is carried out after the heatmap is produced, so you should get it if the dependencies are in place. I will check again once I am back from my holyday, Bruno

**Comment by marsilva248** [comment]
In fact, the heatmap was produced! Thank you so much once again. Have a nice holiday!
Margarida Silva

**Comment by brunocontrerasmoreira** [comment]
See https://github.com/eead-csic-compbio/get_homologues/commit/a6f53942fcc9a573787b5ed87339ed2778f853bc

**Comment by ireneortega** [comment]
@brunocontrerasmoreira I still find problems after downgrading the version of the file `hcluster_pangenome_matrix.sh` as described in [a6f5394](https://github.com/eead-csic-compbio/get_homologues/commit/a6f53942fcc9a573787b5ed87339ed2778f853bc#diff-3361ca2b201a4494437052f91f89eec4413ad66802ae674e9b9411c12ce0c2d4)  :

```
# Plotting file pangenome/heatmap.pdf
Warning message:
In as.dist.default(100 - dfr.num.mat) : non-square matrix
Error in sil.obj[, 1:3] : wrong number of dimensions
Calls: fviz_nbclust -> FUNcluster -> .get_silinfo -> as.data.frame
Execution interrupted
```

The plot is generated as said @marsilva248 but I got that message.

**Comment by brunocontrerasmoreira** [comment]
Hi @ireneortega , can you please:
i) confirm that you have installed the R dependencies
ii) share your input matrix so that me and @pvinuesa can try to reproduce your problem?
Thanks, Bruno

**Comment by ireneortega** [comment]
I think I got confused with plot_matrix_heatmap.sh and hcluster_pangenome_matrix.sh scripts. 

i) This is what I get when checking for the R dependencies:

```
> require("ape")
Loading required package: ape
> require("gplots")
Loading required package: gplots

Attaching package: ‘gplots’

The following object is masked from ‘package:stats’:

    lowess

> require("cluster")
Loading required package: cluster
> require("dendextend")
Loading required package: dendextend

---------------------
Welcome to dendextend version 1.15.1
Type citation('dendextend') for how to cite the package.

Type browseVignettes(package = 'dendextend') for the package vignette.
The github page is: https://github.com/talgalili/dendextend/

Suggestions and bug-reports can be submitted at: https://github.com/talgalili/dendextend/issues
Or contact: <tal.galili@gmail.com>

	To suppress this message use:  suppressPackageStartupMessages(library(dendextend))
---------------------


Attaching package: ‘dendextend’

The following objects are masked from ‘package:ape’:

    ladderize, rotate

The following object is masked from ‘package:stats’:

    cutree

> require("factoextra")
Loading required package: factoextra
Loading required package: ggplot2
Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa
> 
```

ii) This is the input matrix file (I use with theTAB extension, but I changed for uploading here): [pangenome_matrix_t0.txt](https://github.com/eead-csic-compbio/get_homologues/files/6548847/pangenome_matrix_t0.txt)

When I use plot_matrix_heatmap.sh with the input matrix file, this is the message I get:

```
irene@irene-VirtualBox:~/get_homologues-3.4.2$ ./plot_matrix_heatmap.sh -i pangenome_3+2/pangenome_matrix_t0.tab -o pdf -r -H 8 -W 14 -m 28 -t "sample pangenome" -k "genes per cluster"

##############################################################################################
>>> plot_matrix_heatmap.sh vv1.0.4_31Jan18 run started at 2021_05_26-20.19.21
        working directory : /home/irene/get_homologues-3.4.2
        input tab_file : pangenome_3+2/pangenome_matrix_t0.tab | sim_cutoff : 100 | max_decimals : 0
	subset_matrix : 0 | regex : 
        text:sample pangenome|margin_hor:28|margin_vert:18|points:15
	angle:45|charExp:1.0|right_margin:10
        width:14|height:8|outformat:pdf
        reorder_clusters:1|remove_colnames:1|key_xaxis:genes per cluster|do_bioNJ:0
	k:
        
##############################################################################################

# Plotting file pangenome_3+2/pangenome_matrix_t0_heatmap.pdf
Warning message:
In as.dist.default(100 - dfr.num.mat) : non-square matrix
Error in sil.obj[, 1:3] : número incorreto de dimensiones
Calls: fviz_nbclust -> FUNcluster -> .get_silinfo -> as.data.frame
Ejecución interrumpida
>>> file pangenome_3+2/pangenome_matrix_t0_heatmap.pdf was produced

>>> ERROR: file ANDg_meand_silhouette_width_statistic_plot.pdf was NOT produced!

>>> ERROR: file  was NOT produced!
```
although this heatmap is generated [pangenome_matrix_t0_heatmap.pdf](https://github.com/eead-csic-compbio/get_homologues/files/6548944/pangenome_matrix_t0_heatmap.pdf). **I don't understand what does FALSE mean in this plot and I don't know if i should worry about that message.**

When I use hcluster_pangenome_matrix.sh (the downgraded version) with the previous input matrix file, I think it runs correctly:

```
irene@irene-VirtualBox:~/get_homologues-3.4.2$ ./hcluster_pangenome_matrix.sh -i pangenome_3+2/pangenome_matrix_t0.tab -o pdf -H 8 -W 14 -m 28 -t "sample pangenome"
##############################################################################################
>>> hcluster_pangenome_matrix.sh vv1.1_26Jan18 run started at 2021_05_26-20.35.26
        
	# General
	working direcotry:/home/irene/get_homologues-3.4.2
        input tab_file:pangenome_3+2/pangenome_matrix_t0.tab | regex:
	distance:gower|dist_cutoff:|hclustering_meth:ward.D2
	
	# Heatmaps
	cell_note:0
        text:sample pangenome|margin_hor:28|margin_vert:21|points:15
        width:14|height:8|outformat:pdf
	angle:"NULL,NULL"|charExp:0.7
	
	# Goodnes of clustering stats
          * gap satistic
	     n_start:25|n_boot:100|gap_model:
	  * gap and silhouette width
	     k:15
	      
##############################################################################################
>>> Plotting files hclust_gower-ward.D2_pangenome_3+2_pangenome_matrix_t0_tree.pdf and hclust_gower-ward.D2_pangenome_3+2_pangenome_matrix_t0_heatmap.pdf ...
     this will take some time, please be patient

>>> File hclust_gower-ward.D2_pangenome_3+2_pangenome_matrix_t0_tree.pdf was generated
>>> File gower_dist_matrix.tab was generated
>>> File hclust_gower-ward.D2_pangenome_3+2_pangenome_matrix_t0_heatmap.pdf was generated
>>> File hclust_gower-ward.D2_pangenome_3+2_pangenome_matrix_t0_tree.ph was generated
>>> File ./silhouette_width_statistic_plot_ward.D2-gower.pdf was generated
>>> File ./hcluster_ward.D2-gower_cut_at_silhouette_mean_width_k3.pdf was generated
```

Thanks for your help @brunocontrerasmoreira
