### ISSUE TITLE
support for array jobs on SGE cluster

### ISSUE THREAD

**Issue by alexweisberg** [eead-csic-compbio/get_homologues#59]
Hi,

get_homologues has been fantastic for my research and I use it for nearly all of my projects. As time goes on, the datasets I am working with get larger and larger. While submitting the blast search jobs through an SGE queue has tremendously sped things up, with the large datasets there are still a huge numbers of jobs. 

I was wondering if it would be possible to set up the cluster blast jobs as an SGE array job? That way they could all be submitted at once and usage of the cluster could be reviewed and modified by modifying the status of the main job. With an array job there would be one main submission rather than 10s or 100s of thousands of individual jobs. With an array job, I could temporarily pause or scale back the number of CPUs used in case I need to run something else on the cluster, or if someone else needs more CPU time. Thank you!

**Comment by brunocontrerasmoreira** [comment]
Thanks for your suggestion Alex, we will consider it. With the code as it is you can always run your jobs on a dedicated queue and thus control those jobs without affecting other users I guess

**Comment by alexweisberg** [comment]
Hi Bruno,

Thank you for the suggestion. Unfortunately I don’t have access to or the admin ability to create a separate queue. Alternatively, if there could be an option to write all of the commands to a file and then quit, then I could submit that file as an array job and then rerun get_homologues when it finished. The software already works very well and this only becomes an issue for very large datasets or when we troubleshoot something on our cluster, so its not a high priority but it would be convenient. Thanks!

Best,
Alex

**Comment by brunocontrerasmoreira** [comment]
That might be doable, let me check it out on the next few days, Bruno

**Comment by brunocontrerasmoreira** [comment]
Hi Alex, the script could just print to a flat file all the cluster commands. However, they would just a bunch of qsub/bsub commands. I wonder wether you would prefer just the raw commands without any cluster params, etc

**Comment by alexweisberg** [comment]
Hi Bruno,

I think the raw commands would be best. If get_homologues printed the expected cluster params (number of threads etc) to the screen after writing the file that could be useful. Thank you!

Best,
Alex

**Comment by brunocontrerasmoreira** [comment]
Hi Alex, if you git pull you can test get_homologues.pl -m dryrun
It's only partially dry, as it will create output folders and sequence files, but will put the Pfam/BLAST/DIAMOND/orthologues pending jobs in file dryrun.txt in case you want to run those in a cluster

That why you can resume your job anytime and -m dryrun will only write pending jobs.
Let me know if that works for you,
Bruno

**Comment by alexweisberg** [comment]
I was able to test this and it worked very well. Occasionally it would seem to repeat (produce the same list of commands that I already ran) or produce an empty list and die instead of moving on to the next steps. However for the most part it works correctly. Thank you for implementing this!

**Comment by alexweisberg** [comment]
It seems that when I use dryrun, it gets "stuck" at the current step instead of moving on. For example, l use dryrun to generate a list of blast searches, run them as an array job, and then if I run gh again, it produces an empty list of blast searches instead of moving forward and making a list of inparalog searches. The same thing happens at that step. In each case, I have to run it again in local mode until it moves on, then kill the job and run dryrun again in order to make a list of the next step. It's not a big deal since overall it works, but it would be nice if dryrun would move forward if there are zero jobs to be done at the current step.

**Comment by brunocontrerasmoreira** [comment]
Hi @alexweisberg , I actually think that's a good feature as it ensures that all required precomputed files are in place before you can actually move to the next stage.

**Comment by alexweisberg** [comment]
I agree, however it doesn't seem to be working. If I run it with dryrun, compute all of the commands in the file, and then resubmit gh, dryrun produces a new but empty command file, so it appears that all of the commands have finished and there are none remaining, however gh doesn't proceed, it just keeps producing empty command files.

**Comment by eead-csic-compbio** [comment]
Thanks for reporting, I'll fix it

**Comment by eead-csic-compbio** [comment]
Can you please git pull and try out? In my tests it is working now as expected

**Comment by alexweisberg** [comment]
My test run with the new git commit correctly populated the dryrun.txt file with the makeOrtholog commands. Thank you for fixing that!
