### ISSUE TITLE
how to extract core soft core shell and cloud sequences/PAV matrix

### ISSUE THREAD

**Issue by ga23981** [eead-csic-compbio/get_homologues#60]
How can I extract the individual core, soft-core, shell and cloud gene/protein sequences and PAV matrix from the pan-genome. Also , I want to plot dandrograms based on individual PAV matrix and sequences.

**Comment by brunocontrerasmoreira** [comment]
Hi, please check out the manual, those operations are explained there.
For the first task you would need compare_clusters.pl and parse_pangenome_matrix.pl as explained in section "4.8 Performing genome composition analyses"
For plotting dendrograms there's plot_matrix_heatmap.sh, also explained in that section.
Hoipe this helps,
Bruno

**Comment by ga23981** [comment]
Hi,
Thank you for your answer. I am sorry I am unable to understand:

1. How do I extract core sequences?
2. How do I extract shell sequences?
3. How do I extract soft-core sequences?
4. How do I extract cloud sequences?

Similarly, how do I extract the PAV matrix specifically for:
1. core
2. soft-core
3. shell
4. cloud

Is there any directory where I can find gene_ids for these core, soft-core,
shell, cloud genes?

Thank you
Gaurav

**Comment by ga23981** [comment]
Thank you for your help.

**Comment by ga23981** [comment]
Hello,

Could you please suggest which script can I use to plot dendrograms for the
core pavs
cloud pavs
shell pavs
softcore pavs?

Also, I tried to use plot_matrix_heatmap.sh to plot heatmap using my
complete pangenome and it gives me the following error:


plot_matrix_heatmap.sh -i pangenome_matrix_t0.tab o pdf -r -H 8 -W 14 -m 28
-t "pangenome (clusters=180)" -k "genes per cluster"

>>> plot_matrix_heatmap.sh vv1.0.4_31Jan18 run started at
2020_07_08-20.41.03

        working directory :
/scratch/ga23981/bglab/pantoea_alignment/santosh_data_analysis/assembly/plots

        input tab_file : pangenome_matrix_t0.tab | sim_cutoff : 100 |
max_decimals : 0

subset_matrix : 0 | regex :

        text:pangenome_matrix_t0.tab|margin_hor:18|margin_vert:18|points:15

angle:45|charExp:1.0|right_margin:10

        width:15|height:10|outformat:svg

        reorder_clusters:1|remove_colnames:0|key_xaxis:Value|do_bioNJ:0

k:



##############################################################################################


# Plotting file pangenome_matrix_t0_heatmap.svg

Error: There are less than four complete data rows. Pleae revise your input
table!

Execution halted

>>> ERROR: file pangenome_matrix_t0_heatmap.svg was NOT produced.


>>> You can try option -C or alternatively remove columns in the matrix.


>>> file ANDg_meand_silhouette_width_statistic_plot.svg was produced


>>> file ./ANDg_hc_plot_cut_at_mean_silhouette_width_k9.svg was produced



My table seems to be fine though

Thank you
GA

**Comment by brunocontrerasmoreira** [comment]
Hi @ga23981 ,
core (and soft-core) clusters by definition don't have pressence-absence variations (PAVs), so the most interesting for this kind of analysis would be shell & cloud clusters.
You are using the right script, but you should make sure that your pangenome matrix has variation, can you share it with us? Did you compute it with -t 0 clusters?
Bruno

**Comment by ga23981** [comment]
[pan-genome-files.zip](https://github.com/eead-csic-compbio/get_homologues/files/4897555/pan-genome-files.zip)
Hello,
Attached are the five files in a zipped folder,

Pangenome_matrix_t0.tab (this file contains the entire pangenome matrix)

The other 4 files are 
pangenome_cloud_matrix1.tab
pangenome_core_matrix1.tab
pangenome_shell_matrix1.tab
pangenome_softcore_matrix1.tab

I want to plot dendrograms individually using the cloud, shell, softcore and core genomes and also using the entire pangenome matrix.

Yes, I used option -t0

Thank you

**Comment by brunocontrerasmoreira** [comment]
This is how I would do it, note that script requires some R ans some R packages to be installed: 

hcluster_pangenome_matrix.sh -i pangenome_matrix_t0.tab

Please do 

less hcluster_pangenome_matrix.sh

to read about the dependencies and their installation,
Bruno

**Comment by ga23981** [comment]
Thank you, Bruno, it seemed to have worked. 

It generated a few plots but gave error message as well. Could you suggest if there is something that I need to change?

Also, in the PAV matrix some genes have values greater than 1 like 2, 3 or 4. What does this signify? 

/usr/local/apps/gb/GETHOMOLOGUES/1.7.6/hcluster_pangenome_matrix.sh -i ../pangenome_matrix_t0.tab -t "pangenome tree" -a ward.D2 -d gower -o pdf

>>> Plotting files hclust_gower-ward.D2_.._pangenome_matrix_t0_tree.pdf and hclust_gower-ward.D2_.._pangenome_matrix_t0_heatmap.pdf ...
     this will take some time, please be patient

>>> File hclust_gower-ward.D2_.._pangenome_matrix_t0_tree.pdf was generated
>>> File gower_dist_matrix.tab was generated
>>> File hclust_gower-ward.D2_.._pangenome_matrix_t0_heatmap.pdf was generated
>>> File hclust_gower-ward.D2_.._pangenome_matrix_t0_tree.ph was generated
>>> File ./silhouette_width_statistic_plot_ward.D2-gower.pdf was generated
/usr/local/apps/gb/GETHOMOLOGUES/1.7.6/hcluster_pangenome_matrix.sh: line 606: [: too many arguments
>>> ERROR: File ./hcluster_ward.D2-gower_cut_at_silhouette_mean_width_k10.pdf
./hcluster_ward.D2-gower_cut_at_silhouette_mean_width_k11.pdf
./hcluster_ward.D2-gower_cut_at_silhouette_mean_width_k2.pdf
./hcluster_ward.D2-gower_cut_at_silhouette_mean_width_k8.pdf was NOT generated!

Ga

**Comment by brunocontrerasmoreira** [comment]
HI @ga23981 you will see numbers > 1 whenever there are several sequences of the same species in the same cluster, likely inparalogues.
The script tries several thing that might not work with all kinds of data, @pvinuesa can you comment further on the error messages?
Bruno

**Comment by ga23981** [comment]
Hello Bruno,

Could you please suggest if my understanding is correct about the following
pangenome occupancy stats:

Strain cloud shell soft_core core
PANS_1_10 9 762 3794 3153
PANS_1_8 86 704 3782 3153
PANS_1_9 7 759 3794 3153
PANS_200_1 172 468 3784 3153
PANS_2_1 47 691 3796 3153
PANS_4_2 35 646 3797 3153
PANS_99_22 90 664 3793 3153
PANS_99_23 143 591 3784 3153

Using the above stats if I have to plot the number of cloud, shell, soft
core and core genes contributed by each genome then I will need to
subtract the core genes from the soft-core to get the number of soft-core
genes excluding the core genes?

So, for, PANS_1_10 total soft-core genes including the core genes are 3794.
However, soft-core genes excluding the core genes are actually, 3794 - 3153
= 641.

Please help me understand this.

Thank you
GA

**Comment by brunocontrerasmoreira** [comment]
That's correct
