### ISSUE TITLE
trying to run parse_pangenome_matrix.pl -s analyses on a group of 3 bacteria

### ISSUE THREAD

**Issue by sohini5981** [eead-csic-compbio/get_homologues#62]
Hello,

I have been using GET_HOMOLOGOUS for some time now. I am a self taught person when it comes to running codes.Recently I was working with 3 bacterial genomes.While trying to run the  parse_pangenome_matrix.pl on them I was facing a problem.

I ran  the code ./get_homologues.pl -d test7 -t 0 -G on a folder named test7 having 3 genomes.
 Following this, I run the code ./compare_clusters.pl -o test7_intersection -m -d\test7_homologues/.......

Finally I do -
./parse_pangenome_matrix.pl -m test7_intersection/pangenome_matrix_t0.tab -s

the error I get is this
"need at least 5 taxa to perform -s analysis"

Is there any way the code could be modified so that it allows to find the core, shell, and cloud genes among 4 and 3 genomes.

Thank you.

Sohini Guha

**Comment by brunocontrerasmoreira** [comment]
Hi @sohini5981 , Ig guess you could modify the code so that softcore == core, cloud has occuppancy=1 and the rest are shell genes

**Comment by sohini5981** [comment]
[parse_pangenome_matrixmodified.txt](https://github.com/eead-csic-compbio/get_homologues/files/4989987/parse_pangenome_matrixmodified.txt)


Hello again,

I have made a few changes in the code in the lines:647,666,669,799,801,817

I am running GH as we speak and then I would try the modified code.It will be great if you could take a look at it?

Regards
Sohini

**Comment by sohini5981** [comment]
Hello again,
[log.txt](https://github.com/eead-csic-compbio/get_homologues/files/4990513/log.txt)
I ran the modified code and it gave an error.
-bash: ./parse_pangenome_matrixmodified.pl: Permission denied


Regards
Sohini

**Comment by brunocontrerasmoreira** [comment]
Hi @sohini5981 , can't see any changes in the script you sent.
I guess you need to comment out the if statement in https://github.com/eead-csic-compbio/get_homologues/blob/2652414b2dbc867c7abe0cca95f8b0e7a13e3926/parse_pangenome_matrix.pl#L646
and then make sure that
$cloudpos = 1;
possibly in L672

**Comment by brunocontrerasmoreira** [comment]
You should run it as perl parse_pangenome_matrix.pl
