### ISSUE TITLE
get_homologues.pl script do not accept more than 2 cores

### ISSUE THREAD

**Issue by lalomartinez** [eead-csic-compbio/get_homologues#63]
Hi, now I run get_homologues.pl script and use -n option in order to increse the speed of search,  but only run using by default cores (2 cores)

Does anyone know if there is a bug or if a variable has to be changed in the script in order to increase the number of cores?

**Comment by brunocontrerasmoreira** [comment]
Hi @lalomartinez , can you tell us whether you are using the standalone version? Also, how many proteomes are you analyzing?
Thanks, Bruno

**Comment by lalomartinez** [comment]
Hi @brunocontrerasmoreira , I am using the standalone version  09072020 and I am analyzing 33 proteomes of approximately 11,000 proteins for each proteome

**Comment by brunocontrerasmoreira** [comment]
Hello again, I just ran the test:
$ ./get_homologues.pl -d sample_buch_fasta -n 4

And it was running up t o4 BLASTP processes in parallel, so cannot reproduce what you use.
Note that the rest of the processing, other than BLAST/HMMER/DIAMOND will still be using one core, unless you use -m cluster,
Bruno

**Comment by lalomartinez** [comment]
thanks for your help, Eduardo
