### ISSUE TITLE
What is different between complete fungal genome using get_homologues and get_homologues-est?

### ISSUE THREAD

**Issue by sunnycqcn** [eead-csic-compbio/get_homologues#66]
Hello developers,
I want to use get_homologues to analyze my fungal genomes. I have completed annotation them and gotten protein, cds sequences.
I read the manual, which get_homologues-est was used by the non-complete plant genome.
What is the difference between the methods?
Can I use get_homologues to analyze the fungal genome?
Thanks,
Fuyou

**Comment by brunocontrerasmoreira** [comment]
Hi  @sunnycqcn , the main differences between GET_HOMOLOGUES (1) and GET_HOMOLOGUES-EST (2) are:

sequence similarity engine) 1 uses BLASTP as it compares protein sequences by default, whilst 2 uses BLASTN megablast to compare nucleotide sequences expected to be very similar  (see Figure 3 in respective manual)

alignment coverage) 1 assumes peptide/CDS sequences are complete and thus computes coverage with respect to longet sequence, while 2 expects sequences to be incomplete and thus uses the shortest sequence in a pair of aligned seqs to compute coverage (see Figure 4 in respective manual)

isoform filtering) while 1 uses all input sequences, 2 will attempt to remove redundant sequences assuming they are transcript isoforms (see Figure 2 of respective manual)

input data) only 1 can take GenBank files as input, both 1 & 2 can take FASTA files

Hope this helps,
Bruno

**Comment by sunnycqcn** [comment]
Hello Bruno,
Thanks. I get it. So I can use GET_HOMOLOGUES to analyze my complete annotation fungal genome.
Best,
Fuyou

**Comment by brunocontrerasmoreira** [comment]
One last thing. If your genomes are highly similar, with nucleotide identities around 95% you'll probably want BLASTN instead of BLASTP. You can use get_homologues.pl -a "CDS' for that, provided that your input is in GenBank format. The default uses BLASTP to compare peptides, which is better when the distance among your genomes increases, Bruno

**Comment by sunnycqcn** [comment]
Hello Bruno,
I am much appreciated for your suggestions. I checked the parameters. I did not see the parameters for adding or deleting some IDs. If I want to deleting some IDs, I have run them again?
Best,
Fuyou

**Comment by brunocontrerasmoreira** [comment]
Sorry, I don't get it, what do you mean with some IDs? You can use -I too select a subset of the input genomes/proteomes, but if you want to leave some sequences out of the analysis the best thing is to remove them from the input altogether,
Bruno
