### ISSUE TITLE
Docker has get_homologues-est?

### ISSUE THREAD

**Issue by Silverfoxcome** [eead-csic-compbio/get_homologues#68]
Hi!

I wanted to analyses my genomes with get_homologues-est and I wanted to know if the version that is contained in the docker image is only for prokariotes or it also has get_homologues-est?

Thank you so much in advance :D

**Comment by brunocontrerasmoreira** [comment]
Yes it has

**Comment by Silverfoxcome** [comment]
Great!!! Thank you!!!
I'll learn how to use docker just for this program :D

**Comment by brunocontrerasmoreira** [comment]
Thanks, please make sure you read https://github.com/eead-csic-compbio/get_homologues/issues/64 , as @brettChapman explains there how he managed to used the docker image in singularity

**Comment by Silverfoxcome** [comment]
> Thanks, please make sure you read #64 , as @brettChapman explains there how he managed to used the docker image in singularity

I'll read it right away!
Thanks for all the help!

**Comment by brunocontrerasmoreira** [comment]
Thanks, what I mean is that with singularity you can run our docker image with singularity. Read more at  https://singularity.lbl.gov/docs-docker

Please let us know how you manage, I am still to document this,
Bruno
