### ISSUE TITLE
get_homologues or get_homologues-est for chloroplast genomes analysis

### ISSUE THREAD

**Issue by Silverfoxcome** [eead-csic-compbio/get_homologues#69]
Hi!
A question please :) 

I'm working with chloroplast genomes, which are short genomes (~140k-150k) very similar to bacterial genomes. That's why I was thinking of using get_homologues. 
But chloroplast genomes have some genes (less than 20 I think) with introns, so perhaps I should use get_homologues-est that is specific for plant genomes?
I wanted to ask what would be the most suitable program to analyze these genomes?

Thank you so much in advance :)

**Comment by eead-csic-compbio** [comment]
Hi @Silverfoxcome , sorry I only saw this now.
I believe the code extracting CDS sequences from GenBank files should take care of introns, but let me know otherwise. If these are from different species I would go with standard get_homologues.pl, but if they are from the same speies you might want to use -a 'CDS' so that it uses BLASTN instead of BLASTP,
Bruno

**Comment by Silverfoxcome** [comment]
Thank you!

I have ~ 20 cloroplast genome sequences and some are from the same species, but all are from the same genus. In this case, should I better use -a 'CDS' to work with BLASTN?

I was using get_homologues-est.pl because ~ 20 genes of the cloroplast genome have introns. Should I not be concerned about this and use get_homologues.pl and the genbank files?

Thank you so much in advance for all your help.

**Comment by brunocontrerasmoreira** [comment]
Yes, get_homologues.pl with .gbk files should work just fine. You can try first with default params (BLASTP) and then with -a 'CDS' to see if you gain resolution by using BLASTN instead.

**Comment by Silverfoxcome** [comment]
Excelent! I'll try right away and come back with to comment :D 

Thanks a lot in advance!
