### ISSUE TITLE
Number of threads use during clustering

### ISSUE THREAD

**Issue by P-Leao** [eead-csic-compbio/get_homologues#72]
Hi everyone,

Recently I was running the get_homolougues in a few genomes using the following command:
 
./get_homologues.pl -d ~/Genomes/AA -c -n 20 -X -G
 
Later I realized that the program was using the number of threads specify (20) only during the BLAST, and not for the clustering.
Can I change something in this command to allow the program to use more threads during the clustering process?

**Comment by brunocontrerasmoreira** [comment]
Hi Pedro, 
you should be able to use the recently added option -m dryrun and then run the pending tasks with the command [parallel](https://www.gnu.org/software/parallel), as explained at http://eead-csic-compbio.github.io/get_homologues/manual/manual.html#dryrun :+1: 

# 1) run BLASTN (and/or HMMER) in batches
./get_homologues-est.pl -d ~/Genomes/AA -c -X -G -n 20 -o

# 2) run in -m dryrun mode
./get_homologues-est.pl -d ~/Genomes/AA -c -n 20 -X -G -m dryrun
# ...
# EXIT: check the list of pending commands at ~/Genomes/AA_homologues/dryrun.txt
parallel < ~/Genomes/AA_homologues/dryrun.txt

# repeat 2) until completion
./get_homologues-est.pl -d ~/Genomes/AA -m dryrun
# ...

In your case you shouldn't need to start from scratch; to be sure you can remove ~/Genomes/AA_homologues/tmp, and then follow steps 1) and 2) in the recipe. Make sure you have parallel installed by running parallel -V in the terminal, else install it.

Please let us know if that works for you,
Bruno

**Comment by P-Leao** [comment]
Hello Bruno!
Thank you so much for your fast and thoughtful help. the commands worked flawlessly.
I just made one adjust on your instructions.

On the second part of the step 2, when we run parallel, I add the number of threads I want to use (20), otherwise it uses all the available ones. In the end it was like this:
parallel --jobs 20  < ~/Genomes/AA_homologues/dryrun.txt

Once again, thank you for your help! =)
