### ISSUE TITLE
Problem generating ANI due to missing "factoextra"

### ISSUE THREAD

**Issue by TommyH-Tran** [eead-csic-compbio/get_homologues#73]
Hello, 

I am trying create an ANI heatmap at the nucleotide level, but `./plot_matrix_heatmap.sh` is not working due to factoextra no being located. I am using WSL2 Linux on Windows and I am wondering if you know the script to install it? I have tried digging through the internet, could not find anything that worked. 

![factoextraPNG](https://user-images.githubusercontent.com/60275107/115558948-77825880-a270-11eb-8709-698fc6057770.PNG)

**Comment by brunocontrerasmoreira** [comment]
Hi @TommyH-Tran , please type ```./plot_matrix_heatmap.sh -M``` and follow the instructions to install the required R dependencies, hope this helps,
Bruno

**Comment by TommyH-Tran** [comment]
Thanks this worked!
