### ISSUE TITLE
Is there a way to make the pdf outputs from get_homologues into svg files? So, they are easily editable through inkscape or adobe illustrator? 

### ISSUE THREAD

**Issue by TommyH-Tran** [eead-csic-compbio/get_homologues#76]

**Comment by brunocontrerasmoreira** [comment]
I have now updated compare_clusters.pl , parse_pangenome_matrix.pl and plot_pancore_matrix.pl in GitHub. Please try them out and let us know how that goes,
Bruno

**Comment by brunocontrerasmoreira** [comment]
Do you have any feedback on this?

**Comment by TommyH-Tran** [comment]
I have tried out the compare_clusters.pl and it does make the svg file, however the formatting is a bit messy when opened in illustrator as you can see. Although, this can just be fixed with editing probably. 

Pangenome venn pdf
[venn_t0_Cpro.pdf](https://github.com/eead-csic-compbio/get_homologues/files/6710994/venn_t0_Cpro.pdf)

Pangenome venn svg 
![SVGTESTvenn_t0-01](https://user-images.githubusercontent.com/60275107/123305742-12541900-d4e6-11eb-9b36-7bc6de4f30df.png)


Same issue with the parse_pangenome_matrix.pl command. 

Pangenome matrix pdf
[pangenome_matrix_t0__shell.pdf](https://github.com/eead-csic-compbio/get_homologues/files/6711080/pangenome_matrix_t0__shell.pdf)

Pangenome matrix svg
![pangenome_matrix_t0__shell-01](https://user-images.githubusercontent.com/60275107/123306965-88a54b00-d4e7-11eb-8289-8bd4048876a2.png)

I have not had time to test plot_pancore_matrix.pl, but I am going to guess it will follow suite.

**Comment by brunocontrerasmoreira** [comment]
So it seems that Illustrator has trouble with the fonts of SVG plots. Can't you import the PDFs with illustrator? That might be your work around?

**Comment by vinuesa** [comment]
i use pdf2svg for this task:
# sudo apt install pdf2svg
# Usage: pdf2svg <in file.pdf> <out file.svg> [<page no>]
# in your case, the trick is done with the following command:
pdf2svg venn_t0.pdf venn_t0.svg
