### ISSUE TITLE
Trouble creating ANI heatplot

### ISSUE THREAD

**Issue by TommyH-Tran** [eead-csic-compbio/get_homologues#78]
I created the ANI heatplot about 3 months ago, and now I am trying to recreate the plot so I can edit the figure some. However, the output file does not create any image. Is there something I can do fix this?

Here is the input and output code. 

(base) tommy@DESKTOP-D59L9FO:/mnt/c/Users/12542/Downloads/get_homologues$ ./plot_matrix_heatmap.sh -i "/mnt/c/Users/12542/Downloads/get_homologues/Cpro_homologues/prokka1274CJEI_f0_0taxa_CDS_algOMCL_e0_Avg_identity.tab" -d 2 -t "C. pro ANI Matrix" -o tiff

##############################################################################################
        plot_matrix_heatmap.sh vv1.0.4_31Jan18 run started at 2021_07_29-13.34.26
        working directory : /mnt/c/Users/12542/Downloads/get_homologues
        input tab_file : /mnt/c/Users/12542/Downloads/get_homologues/Cpro_homologues/prokka1274CJEI_f0_0taxa_CDS_algOMCL_e0_Avg_identity.tab | sim_cutoff : 100 | max_decimals : 2
        subset_matrix : 0 | regex :
        text:C. pro ANI Matrix|margin_hor:18|margin_vert:18|points:15
        angle:45|charExp:1.0|right_margin:10
        width:15|height:10|outformat:tiff
        reorder_clusters:1|remove_colnames:0|key_xaxis:Value|do_bioNJ:0
        k:

##############################################################################################

Plotting file /mnt/c/Users/12542/Downloads/get_homologues/Cpro_homologues/prokka1274CJEI_f0_0taxa_CDS_algOMCL_e0_Avg_identity_heatmap.tiff
Error in plot.new() : figure margins too large
Calls: heatmap.2 ... image -> image.default -> plot -> plot.default -> plot.new
Error in par(op) : invalid value specified for graphical parameter "pin"
Calls: heatmap.2 -> par
Execution halted

file /mnt/c/Users/12542/Downloads/get_homologues/Cpro_homologues/prokka1274CJEI_f0_0taxa_CDS_algOMCL_e0_Avg_identity_heatmap.tiff was produced

ERROR: file ANDg_meand_silhouette_width_statistic_plot.tiff was NOT produced!

file ./ANDg_hc_plot_cut_at_mean_silhouette_width_k4.svg was produced

**Comment by brunocontrerasmoreira** [comment]
Hi @TommyH-Tran , so this script worked 3 months ago but not now, is that it?
Please share your input file so I can reproduce the error,
Bruno

**Comment by TommyH-Tran** [comment]
It won't let me upload the .tab format of a file here. So I have emailed it to you @brunocontrerasmoreira

**Comment by brunocontrerasmoreira** [comment]
Hi, the script works just fine in my system with R4.1.0 and changing 
    -o tiff
to
    -o pdf

While that TIFF is currently not supported by the script, it might not be difficult to tweak the R code so that it works. Let us know how that goes, Bruno
