### ISSUE TITLE
cloning git doesn't include external binaries

### ISSUE THREAD

**Issue by barrantesisrael** [eead-csic-compbio/get_homologues#8]
After running:

`% ./install.pl`

Comes a message:

```
# mcl binaries are missing
# If you just git cloned you should also get the latest release,
# unpack it and copy the contents of the bin/ folder to your local repo bin/

```
That 'bin/' folder from this git is empty. And I tried compiling MCL on my own, and adding it to the $PATH, but this install script still gives the same error message.

**Comment by eead-csic-compbio** [comment]
Hi Israel, you should do as explained in the tutorial  , in section 2.1.2:

http://digital.csic.es/bitstream/10261/146411/1/pangenome_workshop09032017.html
