### ISSUE TITLE
dryrun.txt file has the same lines for multiple times

### ISSUE THREAD

**Issue by carolynzy** [eead-csic-compbio/get_homologues#80]
Hi, I noticed that I had a very large dryrun.txt file, with more than 880k lines. I have checked with some samples IDs and found that some lines were exactly the same. For example, the following five lines are exactly the same, but appeared in the file at different places( as indicated by the number in the front):

9743:/root/get_homologues-x86_64-20210305/_cluster_makeHomolog.pl -d /mnt/gbk1_homologues -b /mnt/gbk1_homologues/tmp/all.bpo -i 14123.gbk -j 12359.gbk -E 1e-05 -S 0  -C 20 -f 0
114724:/root/get_homologues-x86_64-20210305/_cluster_makeHomolog.pl -d /mnt/gbk1_homologues -b /mnt/gbk1_homologues/tmp/all.bpo -i 14123.gbk -j 12359.gbk -E 1e-05 -S 0  -C 20 -f 0
328807:/root/get_homologues-x86_64-20210305/_cluster_makeHomolog.pl -d /mnt/gbk1_homologues -b /mnt/gbk1_homologues/tmp/all.bpo -i 14123.gbk -j 12359.gbk -E 1e-05 -S 0  -C 20 -f 0
437436:/root/get_homologues-x86_64-20210305/_cluster_makeHomolog.pl -d /mnt/gbk1_homologues -b /mnt/gbk1_homologues/tmp/all.bpo -i 14123.gbk -j 12359.gbk -E 1e-05 -S 0  -C 20 -f 0
731166:/root/get_homologues-x86_64-20210305/_cluster_makeHomolog.pl -d /mnt/gbk1_homologues -b /mnt/gbk1_homologues/tmp/all.bpo -i 14123.gbk -j 12359.gbk -E 1e-05 -S 0  -C 20 -f 0

Is there something wrong with my dryrun.txt file?

**Comment by brunocontrerasmoreira** [comment]
That does not look good, that file should be rewrimyou run. It might be a bug, but might also be due to incomplete previous results?

**Comment by brunocontrerasmoreira** [comment]
I suggest you start off with 10 genomes and see if you can reproduce the error

**Comment by carolynzy** [comment]
I have deleted the tmp folder completely before this run. So it doesn't not caused by the previous run. However, I will try with 10 samples this time. Thank you!

**Comment by carolynzy** [comment]
I have tested with 10 samples and the dryrun.txt file seems fine. I don't what went wrong in the previous run. But I will try my luck and run again with my 420 samples.

**Comment by vinuesa** [comment]
Start out with a clean directory structure - delete the my_gbks_homologues directory before starting over. Keep us posted.

**Comment by carolynzy** [comment]
Hi, @vinuesa , I have removed the tmp folder and repeated the dryrun step. But still I had the same dryrun.txt file. So, if I understand correctly, I should remove all the other files except the blastn output *.blast.gz files, right? If I did so, there will be 420*420= 176400  *.gz files and one "input_order.txt" file in my gbks homologues folder.  Then I should start the dryrun step from this point. I just want to make sure I understand you correctly. Thank you! 

Another question, it seems that I cannot run with multiple threads in the dryrun step, despite I used the -n 63 parameter in the command line. Is there a way to make this possible?

**Comment by carolynzy** [comment]
Just some additional information, when I ran with 10 samples, the dryrun.txt file seemed just fine; but when I did the same thing with 420 samples, then there was a problem. I couldn't figure out why.

**Comment by brunocontrerasmoreira** [comment]
You mean the problem is still there after repeating? The problem with interrupted runs is that you might end up with faulty/empty Blast files. You could remove all those or the whole _homologues folder as suggested by @vinuesa

**Comment by brunocontrerasmoreira** [comment]
> Hi, @vinuesa , I have removed the tmp folder and repeated the dryrun step. But still I had the same dryrun.txt file. So, if I understand correctly, I should remove all the other files except the blastn output _.blast.gz files, right? If I did so, there will be 420_420= 176400 *.gz files and one "input_order.txt" file in my gbks homologues folder. Then I should start the dryrun step from this point. I just want to make sure I understand you correctly. Thank you!
> 
> Another question, it seems that I cannot run with multiple threads in the dryrun step, despite I used the -n 63 parameter in the command line. Is there a way to make this possible?

You are right, -n and dryrun are not compatible, as dryrun does not run any jobs, it just creates the file with commands to be run

**Comment by brunocontrerasmoreira** [comment]
I am now sure there's a bug when you do -m dryrun -c, which exaplins those repeated batch commands. I will fix it and post a corrected script.

**Comment by brunocontrerasmoreira** [comment]
Please see https://github.com/eead-csic-compbio/get_homologues/releases/tag/v3.4.3 or do git pull to fetch the new code.
All your previous (BLAST) results should be reusable, the new code produces dryrun.txt files with no redundancy when using -c.

Since you have a large number of genomes I would recommend that you first run your analyses without -c to see how the job goes (and consider using -s if you have RAM problems). So your command chould be something like 

    $ perl get_homologues.pl -d gbk1 -m dryrun -A -t 0 -P -G

When that run completes you should be able to add -c -z if you wish, but note that runs $NOFSAMPLESREPORT = 10 simulations so that will take a lot longer even if it re-uses as many previous results as possible.
Hope this helps,
Bruno

**Comment by carolynzy** [comment]
@brunocontrerasmoreira , Thank you so much! I will try the new code right away.

**Comment by carolynzy** [comment]
@brunocontrerasmoreira Hi, I have tried the command 

> get_homologues.pl -d gbk1 -m dryrun -A -t 0 -P -G

and got the following message:

> ...
> \# making COGs
> ERROR: find_COGs (/root/get_homologues-x86_64-20210305//bin/COGsoft/COGtriangles/COGtriangles ) failed to terminate job

The COGtriangles.log file shows that:

>LSE completed
>Hitset completed

I don't know what went wrong. What should I do next?

**Comment by brunocontrerasmoreira** [comment]
This could be your job running out of RAM, as your dataset is larger than anything I have tried with bacteria before. Also, I have seen COGtriagnles failing before and then completing just fine on repetition, so I I suggest you repeat that step after removing those files from tmp/ and with more RAM if possible

**Comment by brunocontrerasmoreira** [comment]
You can also try -M instead of -G.

**Comment by carolynzy** [comment]
@brunocontrerasmoreira Thank you for your suggestions. I'm working on this as you suggested. I have one question about the dryrun mode.

According to the manual, the dryrun step should be repeated for several times. If I understand correctly, it should be run at least for three times for 
> _cluster_makeHomolog.pl, 
> _cluster_makeInparalog.pl and 
> _cluster_makeOrtholog.pl

Am I right?

If so, if something went wrong at one step after some other steps already finished, e.g. something went wrong at _cluster_makeHomolog.pl step, and _cluster_makeOrtholog.pl had already finished successfully, where should I resume? Should I delete all the files in the tmp folder and start from the beginning, or just delete the Homologues_xxx files and repeat the dryrun and parallel step? Or something else would you suggest?

I'm asking this because for a large sample set, each step could take several days. It would be really convenient if I don't have to repeat all the steps. 

Thank you very much!

**Comment by brunocontrerasmoreira** [comment]
In your case it should be enouhg to remove from tmp/ all the *homolog* files, but not the *ortholog* ones, does that make sense? 
Bruno

**Comment by carolynzy** [comment]
@brunocontrerasmoreira Yes, that makes sense. I have a follow up question.  
I was stuck at the dryrun mode step, which probably was caused by running out of RAM ( I forgot to add the -s option to the command when repeat it). I have to turn off the computer otherwise it would stall forever. The dryrun.txt file was empty after I did this.  Then I repeated the dryrun step which produced the dryrun.txt file. The first severa lines in the file looks like:

> /root/get_homologues-x86_64-20210828/_cluster_makeHomolog.pl -d /mnt/gbk1_homologues -b /mnt/gbk1_homologues/tmp/all.bpo -i 07MDR10138.gbk -j 07MDR10133.gbk -E 1e-05 -S 0  -C 20 -f 1
>/root/get_homologues-x86_64-20210828/_cluster_makeHomolog.pl -d /mnt/gbk1_homologues -b /mnt/gbk1_homologues/tmp/all.bpo -i 07MDR10142.gbk -j 07MDR10138.gbk -E 1e-05 -S 0  -C 20 -f 1
>/root/get_homologues-x86_64-20210828/_cluster_makeHomolog.pl -d /mnt/gbk1_homologues -b /mnt/gbk1_homologues/tmp/all.bpo -i 07MDR10142.gbk -j 07MDR10133.gbk -E 1e-05 -S 0  -C 20 -f 1

The dryrun.txt file has 176665 lines, which is less than what I supposed it to be 176820 ( 421 * 421 - 421).  I'm not sure this is normal. Is there anything I could do to check if everything is fine?

Thank you!

**Comment by brunocontrerasmoreira** [comment]
The code will skip jobs if the corresponding result files in tmp/ already exist. If you are not sure those existing files are complete you might want to remove all *homologues* files therein and relaunch.

PS: If launching this is only possible with option -s I suspect you might run out of RAM down the line, but you won't know until yo try, right?

Bruno

**Comment by carolynzy** [comment]
@brunocontrerasmoreira Yes, I got it. Thank you very much! You have been of great help.
