### ISSUE TITLE
question "_cluster_makeHomolog.pl" command

### ISSUE THREAD

**Issue by carolynzy** [eead-csic-compbio/get_homologues#82]
Hello, I have a question about the command "_cluster_makeHomolog.pl". 
So, I'm still working with my 421 samples. Now the "_cluster_makeOrthologes.pl" command works as expected, for which the dryrun.txt file contains 88410 lines. 
However, for the "_cluster_makeHomolog.pl" command, there are still less than 176820 lines in the dryrun.txt file (176665). I have deleted the whole tmp folder and repeated twice the whole process after blastn. But I got the same results. And I found it's always the same 126 samples which had less than 840 lines each. 
I'm concerned if this is normal. So, is it possible that "_cluster_makeHomolog.pl" command will omit or pass some sample pairs if they don't meet some criteria? How could I find out what is the cause here? Thank you!

**Comment by brunocontrerasmoreira** [comment]
Hi again @carolynzy , 
the fact that you got the same number of jobs after deleting tmp/ suggests that your observations can be reproduced. Can you confirm this is without arg -c please?
In addition, what do you mean with "less than 840 lines each"?

**Comment by carolynzy** [comment]
Hi, @brunocontrerasmoreira  indeed I have added the -c option. Will that make the difference and how?
With "less than 840 lines each", I mean, because there are 421 samples in total, if each sample is compared with all other samples, there should be 420 pairs; but the same pair of samples has two orders, like A vs B and B vs A, so if I grep one sampe id in the dryrun file, there should be 420 + 420 lines that contain the sample id. I'm not sure my understanding is correct. It's just my guess.

**Comment by brunocontrerasmoreira** [comment]
With -c you simulate how the pangenome grows as more genomes are added to the pool. This is done a number of  $NOFSAMPLESREPORT iterations (default 10) shuffling the genome order. In this context, function makeHomolog is used to count sequences encoded in a new genome which are similar to others in previously added genomes  (according to $MIN_PERSEQID_HOM and $MIN_COVERAGE_HOM). Those sequences are considered not new and thus do not contribute to increase the pangenome size.
This is done in a [loop(https://github.com/eead-csic-compbio/get_homologues/blob/8d1e060d3af90f2bbb1f65fde502e4ada2c911ed/get_homologues.pl#L1846) by comparing pairs of genomes and homologues of genomes i,j are computed only the first time that pair occurs. If the same pair repeats on a posterior iteration, the saved result file if used instead.

**Comment by carolynzy** [comment]
@brunocontrerasmoreira Thank you so much for the clarification. It really helps to understand how the software works.
