### ISSUE TITLE
error in plot_matrix_heatmap.sh

### ISSUE THREAD

**Issue by byeollee** [eead-csic-compbio/get_homologues#85]
Hello,

I got some error

code is
``./plot_matrix_heatmap.sh -i sample_intersection/pangenome_matrix_t0.tab -o pdf -r -W 14 -m 28 -t "sample pangenome (clusters=180)" -k "genes per cluster"

error is

# Plotting file sample_intersection/pangenome_matrix_t0_heatmap.pdf

as.dist.default(100 - dfr.num.mat)에서: non-square matrix
error: 'list' object cannot be coerced to type 'integer'

>>> file sample_intersection/pangenome_matrix_t0_heatmap.pdf was produced

>>> ERROR: file ANDg_meand_silhouette_width_statistic_plot.pdf was NOT produced!

>>> ERROR: file  was NOT produced!

Please help me.. Thank you

And I try to redownload about hcluster file and r package also

**Comment by eead-csic-compbio** [comment]
Hi, as explained in the manual (http://eead-csic-compbio.github.io/get_homologues/manual/manual.html#SECTION00045000000000000000) this scripts takes square matrices. For a pangenome matrix, as in this example, there's hcluster_pangenome_matrix.sh , let me know if this helps,
Bruno
