### ISSUE TITLE
ERROR when plotting pangenome matrix heatmap

### ISSUE THREAD

**Issue by FenggChengg** [eead-csic-compbio/get_homologues#88]
Hi all, 

I got one problem when I used the plot_matrix_heatmap.sh to generate the heatmap for 3 eukaryotic cds fasta. 
It gave the error that: there are less than four complete data rows. Is it because I used less than 5 fasta input here?

![image](https://user-images.githubusercontent.com/77756742/153204363-b5b29d70-d1d7-4c6f-a458-5a66caecb998.png)

**Comment by eead-csic-compbio** [comment]
Hi @FenggChengg , you need at least 4 datasets in order to compute the dendrograms on the margins
