### ISSUE TITLE
clusters lost when using make_nr_pangenome_matrix.pl

### ISSUE THREAD

**Issue by carolynzy** [eead-csic-compbio/get_homologues#89]
Hi,
I'm using  make_nr_pangenome_matrix.pl on my pangenome matrix which contains 9179 clusters.
The code is as below:

> make_nr_pangenome_matrix.pl -m intersection_COG_OMCL_renamed/pangenome_matrix_t0.tab  -n8 -e -C 50 -P

This produced the non-redundant matrix which contains 6460 clusters and 2158 redundant clusters have been merged into the non-redundant clusters.

I found 561 (9179-6460-2158) clusters are lost at this step and there is no information about why these clusters have been filtered out. 
Furthermore, after checking some clusters, I found that some of the 561 lost clusters actually have very high identiy (99%) and coverage (100%, compared to the shortest sequence). I found this very unusually. Would you please look into this? Thank you very much!

**Comment by carolynzy** [comment]
One thing just came to my mind, I used the longest sequence in the each cluster for comparison.  while make_nr_pangenome_matrix.pl used the median sequence. I guess that's what makes the difference. I will check that and update soon.

**Comment by carolynzy** [comment]
I have check two clusters. In neither case the difference between longest sequence and median sequence could explain the lost clusters, since the two were almost identical in these two cases.

For example, cluster1146133 (length=519) has been merged with cluster561552 (length =293),  the aglinment has coverage=88 and identity=93%; meanwhile, cluster 1146133 has aglined to cluster1708201 (length=110) with coverage=110 and identity=100%. However, cluster1708201 was not in the nr matrix.  

If you need the pan genomes sequences I could send it by email. Thank you very much for your time and work!

**Comment by eead-csic-compbio** [comment]
HI @carolynzy , what about cluster1708201 , was it added to another one?
Anyway, thanks for reporting this. Please send the clusters compressed and the matrix file and I'll have a look,
Bruno

**Comment by carolynzy** [comment]
@eead-csic-compbio Thank you! 
The cluster1708201 is not added to any other cluster. I cann't find it in the final non-redundant matrix. 
The same to another 562 clusters (in total 563, because I found two duplicates in the nr matrix, the number of lost clusters is not 561 but 563). 

The dataset is available at : 
https://1drv.ms/u/s!Ahu3aHGoa85Bhq82xQLl3MHKip3d4Q?e=Ptz6Pj

**Comment by eead-csic-compbio** [comment]
Hi @carolynzy , looking into this now. I am curious as to why you are using arg -e , are your sequences transcripts that might be incomplete?

**Comment by carolynzy** [comment]
Yes, without e I got the same results as you did. Thank you very much!
I just have one more question, in what circumstances should I use the e option? I used this option because I thought there could be some errors in the assembly and annotation, or some genes could be disrupted due structure variation, then some CDS would be incomplete. But I think these genes should still be considered as homologs. Maybe I misunderstood something here.

**Comment by eead-csic-compbio** [comment]
Argument -e was meant to be used with clusters of assembled transcripts produced with get_homologues-est.pl. It is common that transcripts assembled de novo, particularly those from lowly expressed genes and sequenced with short reads, are only partial. 
This is opposed to sequences parsed from GenBank files for instance, where you expect that most coding sequences are complete, does this help?
