### ISSUE TITLE
Warning message while downloading uniprot_sprot.fasta.gz

### ISSUE THREAD

**Issue by hliang** [eead-csic-compbio/get_homologues#9]
A warning message in [`install.pl`](https://github.com/eead-csic-compbio/get_homologues/blob/bff1001958822dd42bc1b7eb58871715aaf15731/install.pl#L250)
says "cannot connect to `$BLASTSERVERPATH`: ..." while it is actually trying to download a file (uniprot_sprot.fasta.gz) from server `$SWISSPROTSERVER`. Just a typo I think.

**Comment by eead-csic-compbio** [comment]
Thanks hliang, I just fixed that error message, which you might encounter due to firewall issues or timed-out connections, Bruno
