### ISSUE TITLE
ANI svg

### ISSUE THREAD

**Issue by TommyH-Tran** [eead-csic-compbio/get_homologues#92]
Am I able to get a svg version of the ANI output?

**Comment by eead-csic-compbio** [comment]
You should be able to do so with plot_matrix_heatmap.sh (SVG is the default format)

**Comment by TommyH-Tran** [comment]
is there a flag in the `./plot_matrix_heatmap.sh` command that allows you to adjust the size of the font of the numbers in the boxes of the ANI heat map?

**Comment by eead-csic-compbio** [comment]
Hi @TommyH-Tran ,
there are different options you can try, anything I might have missed @pvinuesa ?

    -d <int> maximum number of decimals in matrix display [0-2; def: 0]
    -p <integer> points for plotting device            [def 15]    
    -H <integer> output device height                  [def 10]    
    -W <integer> output device width                   [def 15]     
    -X <float> character expansion factor              [def 1.0]
