### ISSUE TITLE
Issue with Input files not being detected by Get_homologues 

### ISSUE THREAD

**Issue by apoorva004** [eead-csic-compbio/get_homologues#93]
Hi I have been trying to do comparative genome analysis on 49 genomes of my interest. All the files are in Genbank format. When we run the sample folder, it gives the output but when we run the same command with my input folder, it gives an error. 
Here is my code:

apoorva004@APOORVAGOEL24:~/apoorvahomo/get_homologues-x86_64-20210828$ ./get_homologues.pl -d Prokka_on_collection_49_gbk
/get_homologues.pl -i 0 -d Prokka_on_collection_49_gbk -o 0 -X 0 -e 0 -f 0 -r 0 -t all -c 0 -z 0 -I 0 -m local -n 2 -M 0 -G 0 -p 0 -C 75 -S 1 -E 1e-05 -F 1.5 -N 0 -B 50 -b 0 -s 0 -D 0 -g 0 -a '0' -x 0 -R 0 -A 0 -P 0

 version 28082021
 results_directory=/home/apoorva004/apoorvahomo/get_homologues-x86_64-20210828/Prokka_on_collection_49_gbk_homologues
 parameters: MAXEVALUEBLASTSEARCH=0.01 MAXPFAMSEQS=250 BATCHSIZE=100 KEEPSCNDHSPS=1
 diamond job:0

 checking input files...
Use of uninitialized value $comma_input_files in scalar chop at ./get_homologues.pl line 1055.

 0 genomes, 0 sequences

Illegal division by zero at ./get_homologues.pl line 1114.

**Comment by eead-csic-compbio** [comment]
Hi @apoorva004 , 

1) have you run $ perl instal.pl?

2) can you please show the results of 
    
    ls Prokka_on_collection_49_gbk

3) and share 3 of those files?

Thanks

**Comment by apoorva004** [comment]
[3files.zip](https://github.com/eead-csic-compbio/get_homologues/files/8125358/3files.zip)
  
have you run $ perl instal.pl? Yes 

can you please show the results of

$ ls Prokka_on_collection_49_gbk 
We got the same output as above

and share 3 of those files? I have attached 3 files

**Comment by eead-csic-compbio** [comment]
Hi @apoorva004 , I have renamed your files to match the accepted extensions (see [manual](http://eead-csic-compbio.github.io/get_homologues/manual/manual.html#SECTION00044000000000000000)):

    ls 3files
    2512047070.fna.gb  2523533529.fna.gb  2528768230.fna.gb

It should work for you now. I have updated the script (https://github.com/eead-csic-compbio/get_homologues/commit/0e47131efd36aff9d1874d978b7cbb31afdc76e0) to warn users of this issue, thanks for your feedback,
Bruno

**Comment by eead-csic-compbio** [comment]
Hi @apoorva004 , in order to compute the complete pangenome, including shell and cloud genes, you'll need to compute clusters of all possible sizes with:
    
    get_homologues.pl -t 0

**Comment by apoorva004** [comment]
Thanks @eead-csic-compbio
