### ISSUE TITLE
Phylogeny Question

### ISSUE THREAD

**Issue by TommyH-Tran** [eead-csic-compbio/get_homologues#96]
Does anyone know whether it is better to create a phylogeny using the conservative core genes vs the soft core genes? I know using the conservative core genes is the standard. However, I feel like using the soft core (genes present in 95% of the genomes) might provide higher resolution? Due to the extra genes included. Especially when an outgroup (closely related species to help root the tree) is added.

**Comment by eead-csic-compbio** [comment]
The advantage of core genes, particularly single-copy core core genes, is that they allow multiple clusters to be concatenated seamlessly. I guess your intuition that soft-core genes might increase phylogenetic signal is justified, but that will force to either 
- fill the missing species with gaps ahead of concatenation
- use a phylogeny-building method able to cope with variable number of taxa in the trees

Anything else I might be missing @vinuesa ?
